<?php

/*
   Copyright 2018 Netcarver

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ---------------------------------------------------------------------

   The following data is derived from Google's LibAddressInput project meta-data
   which seems to be released using the Apache license as quoted above.

 */


return [
  'AC'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'ASCENSION ISLAND',
    'zip'=>'ASCN 1ZZ',
    'zipex'=>'ASCN 1ZZ',
  ],
  'AD'=>[
    'admin_area_regex'=>'(?:(Andorra la Vella|Canillo|Encamp|Escaldes-Engordany|La Massana|Ordino|Parròquia d\'Andorra la Vella|Sant Julià de Lòria))',
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'lang'=>'ca',
    'name'=>'ANDORRA',
    'zip'=>'AD[1-7]0\\d',
    'zipex'=>'AD100,AD501,AD700',
  ],
  'AE'=>[
    'admin_area_regex'=>'(?:(أبو ظبي|إمارة الشارقةّ|إمارة دبيّ|إمارة رأس الخيمة|الشارقة|الفجيرة|ام القيوين|دبي|رأس الخيمة|عجمان))',
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'ar',
    'name'=>'UNITED ARAB EMIRATES',
    'require'=>'AS',
    'state_name_type'=>'Emirate',
  ],
  'AF'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'AFGHANISTAN',
    'zip'=>'\\d{4}',
    'zipex'=>'1001,2601,3801',
  ],
  'AG'=>[
    'name'=>'ANTIGUA AND BARBUDA',
    'require'=>'A',
  ],
  'AI'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'ANGUILLA',
    'zip'=>'(?:AI-)?2640',
    'zipex'=>'2640',
  ],
  'AL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'ALBANIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1001,1017,3501',
  ],
  'AM'=>[
    'admin_area_regex'=>'(?:(Արագածոտն|Արարատ|Արմավիր|Գեղարքունիք|Երևան|Լոռի|Կոտայք|Շիրակ|Սյունիք|Վայոց ձոր|Տավուշ))',
    'fmt'=>'%N%n%O%n%A%n%Z%n%C%n%S',
    'lang'=>'hy',
    'name'=>'ARMENIA',
    'zip'=>'(?:37)?\\d{4}',
    'zipex'=>'375010,0002,0010',
  ],
  'AN'=>[
    'name'=>'NETHERLANDS ANTILLES',
  ],
  'AO'=>[
    'name'=>'ANGOLA',
  ],
  'AQ'=>[
    'name'=>'ANTARCTICA',
  ],
  'AR'=>[
    'admin_area_regex'=>'(?:(Buenos Aires|Catamarca|Chaco|Chubut|Ciudad Autónoma de Buenos Aires|Corrientes|Córdoba|Entre Ríos|Formosa|Jujuy|La Pampa|La Rioja|Mendoza|Misiones|Neuquén|Río Negro|Salta|San Juan|San Luis|Santa Cruz|Santa Fe|Santiago del Estero|Tierra del Fuego|Tucumán))',
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'ARGENTINA',
    'upper'=>'ACZ',
    'zip'=>'((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?',
    'zipex'=>'C1070AAM,C1000WAM,B1000TBU,X5187XAB',
  ],
  'AS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'AMERICAN SAMOA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(96799)(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96799',
  ],
  'AT'=>[
    'zip_name_type'=>'PLZ',
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'AUSTRIA',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'1010,3741',
  ],
  'AU'=>[
    'zip_name_type'=>'Postcode',
    'admin_area_regex'=>'(?:(ACT|Australian Capital Territory|NSW|NT|New South Wales|Northern Territory|QLD|Queensland|SA|South Australia|TAS|Tasmania|VIC|Victoria|WA|Western Australia))',
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'lang'=>'en',
    'locality_name_type'=>'Suburb',
    'name'=>'AUSTRALIA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
    'zipex'=>'2060,3171,6430,4000,4006,3001',
  ],
  'AW'=>[
    'name'=>'ARUBA',
  ],
  'AX'=>[
    'fmt'=>'%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    'name'=>'FINLAND',
    'require'=>'ACZ',
    'zip'=>'22\\d{3}',
    'zipex'=>'22150,22550,22240,22710,22270,22730,22430',
  ],
  'AZ'=>[
    'fmt'=>'%N%n%O%n%A%nAZ %Z %C',
    'name'=>'AZERBAIJAN',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'BA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BOSNIA AND HERZEGOVINA',
    'zip'=>'\\d{5}',
    'zipex'=>'71000',
  ],
  'BB'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'name'=>'BARBADOS',
    'state_name_type'=>'Parish',
    'zip'=>'BB\\d{5}',
    'zipex'=>'BB23026,BB22025',
  ],
  'BD'=>[
    'fmt'=>'%N%n%O%n%A%n%C - %Z',
    'name'=>'BANGLADESH',
    'zip'=>'\\d{4}',
    'zipex'=>'1340,1000',
  ],
  'BE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'BELGIUM',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'4000,1000',
  ],
  'BF'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'BURKINA FASO',
  ],
  'BG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BULGARIA (REP.)',
    'zip'=>'\\d{4}',
    'zipex'=>'1000,1700',
  ],
  'BH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BAHRAIN',
    'zip'=>'(?:\\d|1[0-2])\\d{2}',
    'zipex'=>'317',
  ],
  'BI'=>[
    'name'=>'BURUNDI',
  ],
  'BJ'=>[
    'name'=>'BENIN',
    'upper'=>'AC',
  ],
  'BL'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT BARTHELEMY',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'BM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BERMUDA',
    'zip'=>'[A-Z]{2} ?[A-Z0-9]{2}',
    'zipex'=>'FL 07,HM GX,HM 12',
  ],
  'BN'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BRUNEI DARUSSALAM',
    'zip'=>'[A-Z]{2} ?\\d{4}',
    'zipex'=>'BT2328,KA1131,BA1511',
  ],
  'BO'=>[
    'name'=>'BOLIVIA',
    'upper'=>'AC',
  ],
  'BQ'=>[
    'name'=>'BONAIRE, SINT EUSTATIUS, AND SABA',
  ],
  'BR'=>[
    'zip_name_type'=>'CEP',
    'admin_area_regex'=>'(?:(AC|AL|AM|AP|Acre|Alagoas|Amapá|Amazonas|BA|Bahia|CE|Ceará|DF|Distrito Federal|ES|Espírito Santo|GO|Goiás|MA|MG|MS|MT|Maranhão|Mato Grosso|Mato Grosso do Sul|Minas Gerais|PA|PB|PE|PI|PR|Paraná|Paraíba|Pará|Pernambuco|Piauí|RJ|RN|RO|RR|RS|Rio Grande do Norte|Rio Grande do Sul|Rio de Janeiro|Rondônia|Roraima|SC|SE|SP|Santa Catarina|Sergipe|São Paulo|TO|Tocantins))',
    'fmt'=>'%O%n%N%n%A%n%D%n%C-%S%n%Z',
    'lang'=>'pt',
    'name'=>'BRAZIL',
    'require'=>'ASCZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}-?\\d{3}',
    'zipex'=>'40301-110,70002-900',
  ],
  'BS'=>[
    'admin_area_regex'=>'(?:(Abaco|Abaco Islands|Acklins|Andros|Andros Island|Berry Islands|Bimini|Cat Island|Crooked Island|Eleuthera|Exuma|Exuma and Cays|Grand Bahama|Harbour Island|Inagua|Long Island|Mayaguana|N.P.|New Providence|Ragged Island|Rum Cay|San Salvador|Spanish Wells))',
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'BAHAMAS',
    'state_name_type'=>'Island',
  ],
  'BT'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BHUTAN',
    'zip'=>'\\d{5}',
    'zipex'=>'11001,31101,35003',
  ],
  'BV'=>[
    'name'=>'BOUVET ISLAND',
  ],
  'BW'=>[
    'name'=>'BOTSWANA',
  ],
  'BY'=>[
    'fmt'=>'%S%n%Z %C%n%A%n%O%n%N',
    'name'=>'BELARUS',
    'zip'=>'\\d{6}',
    'zipex'=>'223016,225860,220050',
  ],
  'BZ'=>[
    'name'=>'BELIZE',
  ],
  'CA'=>[
    'state_name_type'=>'Province',
    'locality_name_type'=>'Municipality',
    'admin_area_regex'=>'(?:(AB|Alberta|BC|British Columbia|Colombie-Britannique|MB|Manitoba|NB|NL|NS|NT|NU|New Brunswick|Newfoundland and Labrador|Northwest Territories|Nouveau-Brunswick|Nouvelle-Écosse|Nova Scotia|Nunavut|ON|Ontario|PE|Prince Edward Island|QC|Quebec|Québec|SK|Saskatchewan|Terre-Neuve-et-Labrador|Territoires du Nord-Ouest|YT|Yukon|Île-du-Prince-Édouard))',
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'lang'=>'en',
    'name'=>'CANADA',
    'require'=>'ACSZ',
    'upper'=>'ACNOSZ',
    'zip'=>'[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z] ?\\d[ABCEGHJ-NPRSTV-Z]\\d',
    'zipex'=>'H3Z 2Y7,V8X 3X4,T0L 1K0,T0H 1A0,K1A 0B1',
  ],
  'CC'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'COCOS (KEELING) ISLANDS',
    'upper'=>'CS',
    'zip'=>'6799',
    'zipex'=>'6799',
  ],
  'CD'=>[
    'name'=>'CONGO (DEM. REP.)',
  ],
  'CF'=>[
    'name'=>'CENTRAL AFRICAN REPUBLIC',
  ],
  'CG'=>[
    'name'=>'CONGO (REP.)',
  ],
  'CH'=>[
    'fmt'=>'%O%n%N%n%A%nCH-%Z %C',
    'name'=>'SWITZERLAND',
    'require'=>'ACZ',
    'upper'=>'',
    'zip'=>'\\d{4}',
    'zipex'=>'2544,1211,1556,3030',
  ],
  'CI'=>[
    'fmt'=>'%N%n%O%n%X %A %C %X',
    'name'=>'COTE D\'IVOIRE',
  ],
  'CK'=>[
    'name'=>'COOK ISLANDS',
  ],
  'CL'=>[
    'admin_area_regex'=>'(?:(Antofagasta|Araucanía|Arica y Parinacota|Atacama|Aysén|Aysén del General Carlos Ibáñez del Campo|Biobío|Coquimbo|Libertador General Bernardo O\'Higgins|Los Lagos|Los Ríos|Magallanes|Magallanes y de la Antártica Chilena|Maule|Metropolitana de Santiago|O\'Higgins|Región Metropolitana|Tarapacá|Valparaíso))',
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'CHILE',
    'zip'=>'\\d{7}',
    'zipex'=>'8340457,8720019,1230000,8329100',
  ],
  'CM'=>[
    'name'=>'CAMEROON',
  ],
  'CN'=>[
    'admin_area_regex'=>'(?:(上海市|云南省|内蒙古|内蒙古自治区|北京市|台湾|吉林省|四川省|天津市|宁夏|宁夏回族自治区|安徽省|山东省|山西省|广东省|广西|广西壮族自治区|新疆|新疆维吾尔自治区|江苏省|江西省|河北省|河南省|浙江省|海南省|湖北省|湖南省|澳门|甘肃省|福建省|西藏|西藏自治区|贵州省|辽宁省|重庆市|陕西省|青海省|香港|黑龙江省))',
    'fmt'=>'%Z%n%S%C%D%n%A%n%O%n%N',
    'lang'=>'zh',
    'name'=>'CHINA',
    'require'=>'ACSZ',
    'upper'=>'S',
    'zip'=>'\\d{6}',
    'zipex'=>'266033,317204,100096,100808',
  ],
  'CO'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S, %Z',
    'name'=>'COLOMBIA',
    'require'=>'AS',
    'state_name_type'=>'Department',
    'zip'=>'\\d{6}',
    'zipex'=>'111221,130001,760011',
  ],
  'CR'=>[
    'fmt'=>'%N%n%O%n%A%n%S, %C%n%Z',
    'name'=>'COSTA RICA',
    'require'=>'ACS',
    'zip'=>'\\d{4,5}|\\d{3}-\\d{4}',
    'zipex'=>'1000,2010,1001',
  ],
  'CS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
    'zipex'=>'11001',
  ],
  'CV'=>[
    'admin_area_regex'=>'(?:(Boa Vista|Brava|Fogo|Maio|Sal|Santiago|Santo Antão|São Nicolau|São Vicente))',
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'pt',
    'name'=>'CAPE VERDE',
    'state_name_type'=>'Island',
    'zip'=>'\\d{4}',
    'zipex'=>'7600',
  ],
  'CW'=>[
    'name'=>'CURACAO',
  ],
  'CX'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'CHRISTMAS ISLAND',
    'upper'=>'CS',
    'zip'=>'6798',
    'zipex'=>'6798',
  ],
  'CY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CYPRUS',
    'zip'=>'\\d{4}',
    'zipex'=>'2008,3304,1900',
  ],
  'CZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CZECH REP.',
    'zip'=>'\\d{3} ?\\d{2}',
    'zipex'=>'100 00,251 66,530 87,110 00,225 99',
  ],
  'DE'=>[
    'zip_name_type'=>'PLZ',
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GERMANY',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'26133,53225',
  ],
  'DJ'=>[
    'name'=>'DJIBOUTI',
  ],
  'DK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DENMARK',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'8660,1566',
  ],
  'DM'=>[
    'name'=>'DOMINICA',
  ],
  'DO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DOMINICAN REP.',
    'zip'=>'\\d{5}',
    'zipex'=>'11903,10101',
  ],
  'DZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ALGERIA',
    'zip'=>'\\d{5}',
    'zipex'=>'40304,16027',
  ],
  'EC'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'ECUADOR',
    'upper'=>'CZ',
    'zip'=>'\\d{6}',
    'zipex'=>'090105,092301',
  ],
  'EE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ESTONIA',
    'zip'=>'\\d{5}',
    'zipex'=>'69501,11212',
  ],
  'EG'=>[
    'admin_area_regex'=>'(?:(أسوان|أسيوط|الأقصر|الإسكندرية|الإسماعيلية|البحر الأحمر|البحيرة|الجيزة|الدقهلية|السويس|الشرقية|الغربية|الفيوم|القاهرة|القليوبية|المنوفية|المنيا|الوادي الجديد|بني سويف|بورسعيد|جنوب سيناء|دمياط|سوهاج|شمال سيناء|قنا|كفر الشيخ|مطروح))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'lang'=>'ar',
    'name'=>'EGYPT',
    'zip'=>'\\d{5}',
    'zipex'=>'12411,11599',
  ],
  'EH'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'WESTERN SAHARA',
    'zip'=>'\\d{5}',
    'zipex'=>'70000,72000',
  ],
  'ER'=>[
    'name'=>'ERITREA',
  ],
  'ES'=>[
    'admin_area_regex'=>'(?:(A Coruña|Albacete|Alicante|Almería|Asturias|Badajoz|Barcelona|Burgos|Cantabria|Castellón|Ceuta|Ciudad Real|Cuenca|Cáceres|Cádiz|Córdoba|Girona|Granada|Guadalajara|Guipúzcoa|Huelva|Huesca|Islas Baleares|Jaén|La Rioja|Las Palmas|León|Lleida|Lugo|Madrid|Melilla|Murcia|Málaga|Navarra|Ourense|Palencia|Pontevedra|Salamanca|Santa Cruz de Tenerife|Segovia|Sevilla|Soria|Tarragona|Teruel|Toledo|Valencia|Valladolid|Vizcaya|Zamora|Zaragoza|Álava|Ávila))',
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'SPAIN',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'28039,28300,28070',
  ],
  'ET'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ETHIOPIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'FI'=>[
    'fmt'=>'%O%n%N%n%A%nFI-%Z %C',
    'name'=>'FINLAND',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'00550,00011',
  ],
  'FJ'=>[
    'name'=>'FIJI',
  ],
  'FK'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'FALKLAND ISLANDS (MALVINAS)',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'FIQQ 1ZZ',
    'zipex'=>'FIQQ 1ZZ',
  ],
  'FM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MICRONESIA (Federated State of)',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9694[1-4])(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96941,96944',
  ],
  'FO'=>[
    'fmt'=>'%N%n%O%n%A%nFO%Z %C',
    'name'=>'FAROE ISLANDS',
    'zip'=>'\\d{3}',
    'zipex'=>'100',
  ],
  'FR'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRANCE',
    'require'=>'ACZ',
    'upper'=>'CX',
    'zip'=>'\\d{2} ?\\d{3}',
    'zipex'=>'33380,34092,33506',
  ],
  'GA'=>[
    'name'=>'GABON',
  ],
  'GB'=>[
    'locality_name_type'=>'Town',
    'state_name_type'=>'County',
    'zip_name_type'=>'Postcode',
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'UNITED KINGDOM',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}',
    'zipex'=>'EC1Y 8SY,GIR 0AA,M2 5BQ,M34 4AB,CR0 2YR,DN16 9AA,W1A 4ZZ,EC1A 1HQ,OX14 4PG,BS18 8HF,NR25 7HG,RH6 0NP,BH23 6AA,B6 5BA,SO23 9AP,PO1 3AX,BFPO 61',
  ],
  'GD'=>[
    'name'=>'GRENADA (WEST INDIES)',
  ],
  'GE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GEORGIA',
    'zip'=>'\\d{4}',
    'zipex'=>'0101',
  ],
  'GF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRENCH GUIANA',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]3\\d{2}',
    'zipex'=>'97300',
  ],
  'GG'=>[
    'fmt'=>'%N%n%O%n%A%n%C%nGUERNSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'GY\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'GY1 1AA,GY2 2BT',
  ],
  'GH'=>[
    'name'=>'GHANA',
  ],
  'GI'=>[
    'fmt'=>'%N%n%O%n%A%nGIBRALTAR%n%Z',
    'name'=>'GIBRALTAR',
    'require'=>'A',
    'zip'=>'GX11 1AA',
    'zipex'=>'GX11 1AA',
  ],
  'GL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREENLAND',
    'require'=>'ACZ',
    'zip'=>'39\\d{2}',
    'zipex'=>'3900,3950,3911',
  ],
  'GM'=>[
    'name'=>'GAMBIA',
  ],
  'GN'=>[
    'fmt'=>'%N%n%O%n%Z %A %C',
    'name'=>'GUINEA',
    'zip'=>'\\d{3}',
    'zipex'=>'001,200,100',
  ],
  'GP'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'GUADELOUPE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'GQ'=>[
    'name'=>'EQUATORIAL GUINEA',
  ],
  'GR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREECE',
    'require'=>'ACZ',
    'zip'=>'\\d{3} ?\\d{2}',
    'zipex'=>'151 24,151 10,101 88',
  ],
  'GS'=>[
    'fmt'=>'%N%n%O%n%A%n%n%C%n%Z',
    'name'=>'SOUTH GEORGIA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'SIQQ 1ZZ',
    'zipex'=>'SIQQ 1ZZ',
  ],
  'GT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z- %C',
    'name'=>'GUATEMALA',
    'zip'=>'\\d{5}',
    'zipex'=>'09001,01501',
  ],
  'GU'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'GUAM',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96910,96931',
  ],
  'GW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GUINEA-BISSAU',
    'zip'=>'\\d{4}',
    'zipex'=>'1000,1011',
  ],
  'GY'=>[
    'name'=>'GUYANA',
  ],
  'HK'=>[
    'admin_area_regex'=>'(?:(九龍|新界|香港島))',
    'fmt'=>'%S%n%C%n%A%n%O%n%N',
    'lang'=>'zh-Hant',
    'locality_name_type'=>'District',
    'name'=>'HONG KONG',
    'require'=>'AS',
    'state_name_type'=>'Area',
    'upper'=>'S',
  ],
  'HM'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'HEARD AND MCDONALD ISLANDS',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
    'zipex'=>'7050',
  ],
  'HN'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S%n%Z',
    'name'=>'HONDURAS',
    'require'=>'ACS',
    'zip'=>'\\d{5}',
    'zipex'=>'31301',
  ],
  'HR'=>[
    'fmt'=>'%N%n%O%n%A%nHR-%Z %C',
    'name'=>'CROATIA',
    'zip'=>'\\d{5}',
    'zipex'=>'10000,21001,10002',
  ],
  'HT'=>[
    'fmt'=>'%N%n%O%n%A%nHT%Z %C',
    'name'=>'HAITI',
    'zip'=>'\\d{4}',
    'zipex'=>'6120,5310,6110,8510',
  ],
  'HU'=>[
    'fmt'=>'%N%n%O%n%C%n%A%n%Z',
    'name'=>'HUNGARY (Rep.)',
    'require'=>'ACZ',
    'upper'=>'ACNO',
    'zip'=>'\\d{4}',
    'zipex'=>'1037,2380,1540',
  ],
  'ID'=>[
    'admin_area_regex'=>'(?:(Aceh|Bali|Banten|Bengkulu|DKI Jakarta|Daerah Istimewa Yogyakarta|Gorontalo|Jambi|Jawa Barat|Jawa Tengah|Jawa Timur|Kalimantan Barat|Kalimantan Selatan|Kalimantan Tengah|Kalimantan Timur|Kalimantan Utara|Kepulauan Bangka Belitung|Kepulauan Riau|Lampung|Maluku|Maluku Utara|Nusa Tenggara Barat|Nusa Tenggara Timur|Papua|Papua Barat|Riau|Sulawesi Barat|Sulawesi Selatan|Sulawesi Tengah|Sulawesi Tenggara|Sulawesi Utara|Sumatera Barat|Sumatera Selatan|Sumatera Utara))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S %Z',
    'lang'=>'id',
    'name'=>'INDONESIA',
    'require'=>'AS',
    'zip'=>'\\d{5}',
    'zipex'=>'40115',
  ],
  'IE'=>[
    'zip_name_type'=>'eircode',
    'admin_area_regex'=>'(?:(Co. Carlow|Co. Cavan|Co. Clare|Co. Cork|Co. Donegal|Co. Dublin|Co. Galway|Co. Kerry|Co. Kildare|Co. Kilkenny|Co. Laois|Co. Leitrim|Co. Limerick|Co. Longford|Co. Louth|Co. Mayo|Co. Meath|Co. Monaghan|Co. Offaly|Co. Roscommon|Co. Sligo|Co. Tipperary|Co. Waterford|Co. Westmeath|Co. Wexford|Co. Wicklow))',
    'fmt'=>'%N%n%O%n%A%n%D%n%C%n%S %Z',
    'lang'=>'en',
    'name'=>'IRELAND',
    'state_name_type'=>'County',
    'zip'=>'[\\dA-Z]{3} ?[\\dA-Z]{4}',
    'zipex'=>'A65 F4E2',
  ],
  'IL'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'ISRAEL',
    'zip'=>'\\d{5}(?:\\d{2})?',
    'zipex'=>'9614303',
  ],
  'IM'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'ISLE OF MAN',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'IM\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'IM2 1AA,IM99 1PS',
  ],
  'IN'=>[
    'zip_name_type'=>'pin',
    'admin_area_regex'=>'(?:(Andaman & Nicobar|Andaman and Nicobar Islands|Andhra Pradesh|Arunachal Pradesh|Assam|Bihar|Chandigarh|Chhattisgarh|Dadra & Nagar Haveli|Dadra and Nagar Haveli|Daman & Diu|Daman and Diu|Delhi|Goa|Gujarat|Haryana|Himachal Pradesh|Jammu & Kashmir|Jammu and Kashmir|Jharkhand|Karnataka|Kerala|Lakshadweep|Madhya Pradesh|Maharashtra|Manipur|Meghalaya|Mizoram|Nagaland|Odisha|Puducherry|Punjab|Rajasthan|Sikkim|Tamil Nadu|Telangana|Tripura|Uttar Pradesh|Uttarakhand|West Bengal))',
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'INDIA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'zip'=>'\\d{6}',
    'zipex'=>'110034,110001',
  ],
  'IO'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'BRITISH INDIAN OCEAN TERRITORY',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'BBND 1ZZ',
    'zipex'=>'BBND 1ZZ',
  ],
  'IQ'=>[
    'fmt'=>'%O%n%N%n%A%n%C, %S%n%Z',
    'name'=>'IRAQ',
    'require'=>'ACS',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'31001',
  ],
  'IR'=>[
    'fmt'=>'%O%n%N%n%S%n%C, %D%n%A%n%Z',
    'name'=>'IRAN',
    'zip'=>'\\d{5}-?\\d{5}',
    'zipex'=>'11936-12345',
  ],
  'IS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ICELAND',
    'zip'=>'\\d{3}',
    'zipex'=>'320,121,220,110',
  ],
  'IT'=>[
    'zip_name_type'=>'CAP',
    'admin_area_regex'=>'(?:(AG|AL|AN|AO|AP|AQ|AR|AT|AV|Agrigento|Alessandria|Ancona|Aosta|Arezzo|Ascoli Piceno|Asti|Avellino|BA|BG|BI|BL|BN|BO|BR|BS|BT|BZ|Bari|Barletta-Andria-Trani|Belluno|Benevento|Bergamo|Biella|Bologna|Bolzano|Brescia|Brindisi|CA|CB|CE|CH|CI|CL|CN|CO|CR|CS|CT|CZ|Cagliari|Caltanissetta|Campobasso|Carbonia-Iglesias|Caserta|Catania|Catanzaro|Chieti|Como|Cosenza|Cremona|Crotone|Cuneo|EN|Enna|FC|FE|FG|FI|FM|FR|Fermo|Ferrara|Firenze|Foggia|Forlì-Cesena|Frosinone|GE|GO|GR|Genova|Gorizia|Grosseto|IM|IS|Imperia|Isernia|KR|L\'Aquila|LC|LE|LI|LO|LT|LU|La Spezia|Latina|Lecce|Lecco|Livorno|Lodi|Lucca|MB|MC|ME|MI|MN|MO|MS|MT|Macerata|Mantova|Massa-Carrara|Matera|Medio Campidano|Messina|Milano|Modena|Monza e Brianza|NA|NO|NU|Napoli|Novara|Nuoro|OG|OR|OT|Ogliastra|Olbia-Tempio|Oristano|PA|PC|PD|PE|PG|PI|PN|PO|PR|PT|PU|PV|PZ|Padova|Palermo|Parma|Pavia|Perugia|Pesaro e Urbino|Pescara|Piacenza|Pisa|Pistoia|Pordenone|Potenza|Prato|RA|RC|RE|RG|RI|RM|RN|RO|Ragusa|Ravenna|Reggio Calabria|Reggio Emilia|Rieti|Rimini|Roma|Rovigo|SA|SI|SO|SP|SR|SS|SV|Salerno|Sassari|Savona|Siena|Siracusa|Sondrio|TA|TE|TN|TO|TP|TR|TS|TV|Taranto|Teramo|Terni|Torino|Trapani|Trento|Treviso|Trieste|UD|Udine|VA|VB|VC|VE|VI|VR|VS|VT|VV|Varese|Venezia|Verbano-Cusio-Ossola|Vercelli|Verona|Vibo Valentia|Vicenza|Viterbo))',
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'it',
    'name'=>'ITALY',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'00144,47037,39049',
  ],
  'JE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%nJERSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'JE\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'JE1 1AA,JE2 2BT',
  ],
  'JM'=>[
    'admin_area_regex'=>'(?:(Clarendon|Hanover|Kingston|Manchester|Portland|St. Andrew|St. Ann|St. Catherine|St. Elizabeth|St. James|St. Mary|St. Thomas|Trelawny|Westmoreland))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S %X',
    'lang'=>'en',
    'name'=>'JAMAICA',
    'require'=>'ACS',
    'state_name_type'=>'Parish',
  ],
  'JO'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'JORDAN',
    'zip'=>'\\d{5}',
    'zipex'=>'11937,11190',
  ],
  'JP'=>[
    'admin_area_regex'=>'(?:(三重県|京都府|佐賀県|兵庫県|北海道|千葉県|和歌山県|埼玉県|大分県|大阪府|奈良県|宮城県|宮崎県|富山県|山口県|山形県|山梨県|岐阜県|岡山県|岩手県|島根県|広島県|徳島県|愛媛県|愛知県|新潟県|東京都|栃木県|沖縄県|滋賀県|熊本県|石川県|神奈川県|福井県|福岡県|福島県|秋田県|群馬県|茨城県|長崎県|長野県|青森県|静岡県|香川県|高知県|鳥取県|鹿児島県))',
    'fmt'=>'〒%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'ja',
    'name'=>'JAPAN',
    'require'=>'ACSZ',
    'state_name_type'=>'Prefecture',
    'upper'=>'S',
    'zip'=>'\\d{3}-?\\d{4}',
    'zipex'=>'154-0023,350-1106,951-8073,112-0001,208-0032,231-0012',
  ],
  'KE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'KENYA',
    'zip'=>'\\d{5}',
    'zipex'=>'20100,00100',
  ],
  'KG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KYRGYZSTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'720001',
  ],
  'KH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'CAMBODIA',
    'zip'=>'\\d{5}',
    'zipex'=>'12203,14206,12000',
  ],
  'KI'=>[
    'fmt'=>'%N%n%O%n%A%n%S%n%C',
    'name'=>'KIRIBATI',
    'state_name_type'=>'Island',
    'upper'=>'ACNOS',
  ],
  'KM'=>[
    'name'=>'COMOROS',
    'upper'=>'AC',
  ],
  'KN'=>[
    'admin_area_regex'=>'(?:(Nevis|St. Kitts))',
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'SAINT KITTS AND NEVIS',
    'require'=>'ACS',
    'state_name_type'=>'Island',
  ],
  'KR'=>[
    'admin_area_regex'=>'(?:(강원|강원도|경기|경기도|경남|경북|경상남도|경상북도|광주|광주광역시|대구|대구광역시|대전|대전광역시|부산|부산광역시|서울|서울특별시|세종|세종특별자치시|울산|울산광역시|인천|인천광역시|전남|전라남도|전라북도|전북|제주|제주특별자치도|충남|충북|충청남도|충청북도))',
    'fmt'=>'%S %C%D%n%A%n%O%n%N%n%Z',
    'lang'=>'ko',
    'name'=>'SOUTH KOREA',
    'require'=>'ACSZ',
    'state_name_type'=>'Do Si',
    'upper'=>'Z',
    'zip'=>'\\d{5}',
    'zipex'=>'03051',
  ],
  'KW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KUWAIT',
    'zip'=>'\\d{5}',
    'zipex'=>'54541,54551,54404,13009',
  ],
  'KY'=>[
    'admin_area_regex'=>'(?:(Cayman Brac|Grand Cayman|Little Cayman))',
    'fmt'=>'%N%n%O%n%A%n%S %Z',
    'lang'=>'en',
    'name'=>'CAYMAN ISLANDS',
    'require'=>'AS',
    'state_name_type'=>'Island',
    'zip'=>'KY\\d-\\d{4}',
    'zipex'=>'KY1-1100,KY1-1702,KY2-2101',
  ],
  'KZ'=>[
    'fmt'=>'%Z%n%S%n%C%n%A%n%O%n%N',
    'name'=>'KAZAKHSTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'040900,050012',
  ],
  'LA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'LAO (PEOPLE\'S DEM. REP.)',
    'zip'=>'\\d{5}',
    'zipex'=>'01160,01000',
  ],
  'LB'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LEBANON',
    'zip'=>'(?:\\d{4})(?: ?(?:\\d{4}))?',
    'zipex'=>'2038 3054,1107 2810,1000',
  ],
  'LC'=>[
    'name'=>'SAINT LUCIA',
  ],
  'LI'=>[
    'zip_name_type'=>'Zip Code',
    'fmt'=>'%O%n%N%n%A%nFL-%Z %C',
    'name'=>'LIECHTENSTEIN',
    'require'=>'ACZ',
    'zip'=>'948[5-9]|949[0-7]',
    'zipex'=>'9496,9491,9490,9485',
  ],
  'LK'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SRI LANKA',
    'zip'=>'\\d{5}',
    'zipex'=>'20000,00100',
  ],
  'LR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'LIBERIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'LS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LESOTHO',
    'zip'=>'\\d{3}',
    'zipex'=>'100',
  ],
  'LT'=>[
    'fmt'=>'%O%n%N%n%A%nLT-%Z %C',
    'name'=>'LITHUANIA',
    'zip'=>'\\d{5}',
    'zipex'=>'04340,03500',
  ],
  'LU'=>[
    'fmt'=>'%O%n%N%n%A%nL-%Z %C',
    'name'=>'LUXEMBOURG',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'4750,2998',
  ],
  'LV'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %Z',
    'name'=>'LATVIA',
    'zip'=>'LV-\\d{4}',
    'zipex'=>'LV-1073,LV-1000',
  ],
  'LY'=>[
    'name'=>'LIBYA',
  ],
  'MA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MOROCCO',
    'zip'=>'\\d{5}',
    'zipex'=>'53000,10000,20050,16052',
  ],
  'MC'=>[
    'fmt'=>'%N%n%O%n%A%nMC-%Z %C %X',
    'name'=>'MONACO',
    'zip'=>'980\\d{2}',
    'zipex'=>'98000,98020,98011,98001',
  ],
  'MD'=>[
    'fmt'=>'%N%n%O%n%A%nMD-%Z %C',
    'name'=>'Rep. MOLDOVA',
    'zip'=>'\\d{4}',
    'zipex'=>'2012,2019',
  ],
  'ME'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MONTENEGRO',
    'zip'=>'8\\d{4}',
    'zipex'=>'81257,81258,81217,84314,85366',
  ],
  'MF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT MARTIN',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'MG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MADAGASCAR',
    'zip'=>'\\d{3}',
    'zipex'=>'501,101',
  ],
  'MH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MARSHALL ISLANDS',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969[67]\\d)(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96960,96970',
  ],
  'MK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MACEDONIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1314,1321,1443,1062',
  ],
  'ML'=>[
    'name'=>'MALI',
  ],
  'MM'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %Z',
    'name'=>'MYANMAR',
    'zip'=>'\\d{5}',
    'zipex'=>'11181',
  ],
  'MN'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S %Z',
    'name'=>'MONGOLIA',
    'zip'=>'\\d{5}',
    'zipex'=>'65030,65270',
  ],
  'MO'=>[
    'fmt'=>'%A%n%O%n%N',
    'name'=>'MACAO',
    'require'=>'A',
  ],
  'MP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'NORTHERN MARIANA ISLANDS',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9695[012])(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96950,96951,96952',
  ],
  'MQ'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MARTINIQUE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]2\\d{2}',
    'zipex'=>'97220',
  ],
  'MR'=>[
    'name'=>'MAURITANIA',
    'upper'=>'AC',
  ],
  'MS'=>[
    'name'=>'MONTSERRAT',
  ],
  'MT'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALTA',
    'upper'=>'CZ',
    'zip'=>'[A-Z]{3} ?\\d{2,4}',
    'zipex'=>'NXR 01,ZTN 05,GPO 01,BZN 1130,SPB 6031,VCT 1753',
  ],
  'MU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'MAURITIUS',
    'upper'=>'CZ',
    'zip'=>'\\d{3}(?:\\d{2}|[A-Z]{2}\\d{3})',
    'zipex'=>'42602',
  ],
  'MV'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALDIVES',
    'zip'=>'\\d{5}',
    'zipex'=>'20026',
  ],
  'MW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'MALAWI',
  ],
  'MX'=>[
    'admin_area_regex'=>'(?:(AGS|Aguascalientes|BC|BCS|Baja California|Baja California Sur|CAMP|CDMX|CHIH|CHIS|COAH|COL|Campeche|Chiapas|Chihuahua|Ciudad de México|Coahuila|Colima|DGO|Durango|Estado de México|GRO|GTO|Guanajuato|Guerrero|HGO|Hidalgo|JAL|Jalisco|MEX|MICH|MOR|Michoacán|Morelos|NAY|NL|Nayarit|Nuevo León|OAX|Oaxaca|PUE|Puebla|QRO|QROO|Querétaro|Quintana Roo|SIN|SLP|SON|San Luís Potosí|Sinalóa|Sonora|TAB|TAMPS|TLAX|Tabasco|Tamaulipas|Tlaxcala|VER|Veracruz|YUC|Yucatán|ZAC|Zacatecas))',
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C, %S',
    'lang'=>'es',
    'name'=>'MEXICO',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CSZ',
    'zip'=>'\\d{5}',
    'zipex'=>'02860,77520,06082',
  ],
  'MY'=>[
    'admin_area_regex'=>'(?:(Johor|Kedah|Kelantan|Kuala Lumpur|Labuan|Melaka|Negeri Sembilan|Pahang|Perak|Perlis|Pulau Pinang|Putrajaya|Sabah|Sarawak|Selangor|Terengganu))',
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C%n%S',
    'lang'=>'ms',
    'name'=>'MALAYSIA',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'43000,50754,88990,50670',
  ],
  'MZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MOZAMBIQUE',
    'zip'=>'\\d{4}',
    'zipex'=>'1102,1119,3212',
  ],
  'NA'=>[
    'name'=>'NAMIBIA',
  ],
  'NC'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'NEW CALEDONIA',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'988\\d{2}',
    'zipex'=>'98814,98800,98810',
  ],
  'NE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'NIGER',
    'zip'=>'\\d{4}',
    'zipex'=>'8001',
  ],
  'NF'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'NORFOLK ISLAND',
    'upper'=>'CS',
    'zip'=>'2899',
    'zipex'=>'2899',
  ],
  'NG'=>[
    'admin_area_regex'=>'(?:(Abia|Adamawa|Akwa Ibom|Anambra|Bauchi|Bayelsa|Benue|Borno|Cross River|Delta|Ebonyi|Edo|Ekiti|Enugu|Federal Capital Territory|Gombe|Imo|Jigawa|Kaduna|Kano|Katsina|Kebbi|Kogi|Kwara|Lagos|Nasarawa|Niger|Ogun State|Ondo|Osun|Oyo|Plateau|Rivers|Sokoto|Taraba|Yobe|Zamfara))',
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'NIGERIA',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{6}',
    'zipex'=>'930283,300001,931104',
  ],
  'NI'=>[
    'admin_area_regex'=>'(?:(Boaco|Carazo|Chinandega|Chontales|Esteli|Granada|Jinotega|Leon|Madriz|Managua|Masaya|Matagalpa|Nueva Segovia|Raan|Raas|Rio San Juan|Rivas))',
    'fmt'=>'%N%n%O%n%A%n%Z%n%C, %S',
    'lang'=>'es',
    'name'=>'NICARAGUA',
    'state_name_type'=>'Department',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'52000',
  ],
  'NL'=>[
    'zip_name_type'=>'Postcode',
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'NETHERLANDS',
    'require'=>'ACZ',
    'zip'=>'\\d{4} ?[A-Z]{2}',
    'zipex'=>'1234 AB,2490 AA',
  ],
  'NO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'locality_name_type'=>'Town',
    'name'=>'NORWAY',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'0025,0107,6631',
  ],
  'NP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'NEPAL',
    'zip'=>'\\d{5}',
    'zipex'=>'44601',
  ],
  'NR'=>[
    'admin_area_regex'=>'(?:(Aiwo District|Anabar District|Anetan District|Anibare District|Baiti District|Boe District|Buada District|Denigomodu District|Ewa District|Ijuw District|Meneng District|Nibok District|Uaboe District|Yaren District))',
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'en',
    'name'=>'NAURU CENTRAL PACIFIC',
    'require'=>'AS',
    'state_name_type'=>'District',
  ],
  'NU'=>[
    'name'=>'NIUE',
  ],
  'NZ'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C %Z',
    'name'=>'NEW ZEALAND',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'6001,6015,6332,8252,1030',
  ],
  'OM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'OMAN',
    'zip'=>'(?:PC )?\\d{3}',
    'zipex'=>'133,112,111',
  ],
  'PA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'PANAMA (REP.)',
    'upper'=>'CS',
  ],
  'PE'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'name'=>'PERU',
    'zip'=>'(?:LIMA \\d{1,2}|CALLAO 0?\\d)|[0-2]\\d{4}',
    'zipex'=>'LIMA 23,LIMA 42,CALLAO 2,02001',
  ],
  'PF'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'name'=>'FRENCH POLYNESIA',
    'require'=>'ACSZ',
    'state_name_type'=>'Island',
    'upper'=>'CS',
    'zip'=>'987\\d{2}',
    'zipex'=>'98709',
  ],
  'PG'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z %S',
    'name'=>'PAPUA NEW GUINEA',
    'require'=>'ACS',
    'zip'=>'\\d{3}',
    'zipex'=>'111',
  ],
  'PH'=>[
    'admin_area_regex'=>'(?:(Abra|Agusan del Norte|Agusan del Sur|Aklan|Albay|Antique|Apayao|Aurora|Basilan|Bataan|Batanes|Batangas|Benguet|Biliran|Bohol|Bukidnon|Bulacan|Cagayan|Camarines Norte|Camarines Sur|Camiguin|Capiz|Catanduanes|Cavite|Cebu|Compostela Valley|Cotabato|Davao Occidental|Davao Oriental|Davao del Norte|Davao del Sur|Dinagat Islands|Eastern Samar|Guimaras|Ifugao|Ilocos Norte|Ilocos Sur|Iloilo|Isabela|Kalinga|La Union|Laguna|Lanao del Norte|Lanao del Sur|Leyte|Maguindanao|Marinduque|Masbate|Metro Manila|Mindoro Occidental|Mindoro Oriental|Misamis Occidental|Misamis Oriental|Mountain Province|Negros Occidental|Negros Oriental|Northern Samar|Nueva Ecija|Nueva Vizcaya|Palawan|Pampanga|Pangasinan|Quezon Province|Quirino|Rizal|Romblon|Samar|Sarangani|Siquijor|Sorsogon|South Cotabato|Southern Leyte|Sultan Kudarat|Sulu|Surigao del Norte|Surigao del Sur|Tarlac|Tawi-Tawi|Zambales|Zamboanga Sibuguey|Zamboanga del Norte|Zamboanga del Sur))',
    'fmt'=>'%N%n%O%n%A%n%D, %C%n%Z %S',
    'lang'=>'en',
    'name'=>'PHILIPPINES',
    'zip'=>'\\d{4}',
    'zipex'=>'1008,1050,1135,1207,2000,1000',
  ],
  'PK'=>[
    'fmt'=>'%N%n%O%n%A%n%C-%Z',
    'name'=>'PAKISTAN',
    'zip'=>'\\d{5}',
    'zipex'=>'44000',
  ],
  'PL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'POLAND',
    'require'=>'ACZ',
    'zip'=>'\\d{2}-\\d{3}',
    'zipex'=>'00-950,05-470,48-300,32-015,00-940',
  ],
  'PM'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'ST. PIERRE AND MIQUELON',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]5\\d{2}',
    'zipex'=>'97500',
  ],
  'PN'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'PITCAIRN',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'PCRN 1ZZ',
    'zipex'=>'PCRN 1ZZ',
  ],
  'PR'=>[
    'fmt'=>'%N%n%O%n%A%n%C PR %Z',
    'name'=>'PUERTO RICO',
    'require'=>'ACZ',
    'upper'=>'ACNO',
    'zip'=>'(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'00930',
  ],
  'PS'=>[
    'name'=>'PALESTINIAN TERRITORY',
  ],
  'PT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PORTUGAL',
    'require'=>'ACZ',
    'zip'=>'\\d{4}-\\d{3}',
    'zipex'=>'2725-079,1250-096,1201-950,2860-571,1208-148',
  ],
  'PW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'PALAU',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:39|40))(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'96940',
  ],
  'PY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PARAGUAY',
    'zip'=>'\\d{4}',
    'zipex'=>'1536,1538,1209',
  ],
  'QA'=>[
    'name'=>'QATAR',
    'upper'=>'AC',
  ],
  'RE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'REUNION',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]4\\d{2}',
    'zipex'=>'97400',
  ],
  'RO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ROMANIA',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
    'zipex'=>'060274,061357,200716',
  ],
  'RS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'REPUBLIC OF SERBIA',
    'zip'=>'\\d{5,6}',
    'zipex'=>'106314',
  ],
  'RU'=>[
    'admin_area_regex'=>'(?:(Автономна Республіка Крим|Алтайский край|Амурская область|Архангельская область|Астраханская область|Белгородская область|Брянская область|Владимирская область|Волгоградская область|Вологодская область|Воронежская область|Еврейская автономная область|Забайкальский край|Ивановская область|Иркутская область|Кабардино-Балкарская Республика|Калининградская область|Калужская область|Камчатский край|Карачаево-Черкесская Республика|Кемеровская область|Кировская область|Костромская область|Краснодарский край|Красноярский край|Курганская область|Курская область|Ленинградская область|Липецкая область|Магаданская область|Москва|Московская область|Мурманская область|Ненецкий автономный округ|Нижегородская область|Новгородская область|Новосибирская область|Омская область|Оренбургская область|Орловская область|Пензенская область|Пермский край|Приморский край|Псковская область|Республика Адыгея|Республика Алтай|Республика Башкортостан|Республика Бурятия|Республика Дагестан|Республика Ингушетия|Республика Калмыкия|Республика Карелия|Республика Коми|Республика Крым|Республика Марий Эл|Республика Мордовия|Республика Саха (Якутия)|Республика Северная Осетия-Алания|Республика Татарстан|Республика Тыва|Республика Удмуртия|Республика Хакасия|Ростовская область|Рязанская область|Самарская область|Санкт-Петербург|Саратовская область|Сахалинская область|Свердловская область|Севастополь|Смоленская область|Ставропольский край|Тамбовская область|Тверская область|Томская область|Тульская область|Тюменская область|Ульяновская область|Хабаровский край|Ханты-Мансийский автономный округ|Челябинская область|Чеченская Республика|Чувашская Республика|Чукотский автономный округ|Ямало-Ненецкий автономный округ|Ярославская область|город Москва|город Санкт-Петербург|город Севастополь))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'lang'=>'ru',
    'name'=>'RUSSIAN FEDERATION',
    'require'=>'ACSZ',
    'state_name_type'=>'Oblast',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
    'zipex'=>'247112,103375,188300',
  ],
  'RW'=>[
    'name'=>'RWANDA',
    'upper'=>'AC',
  ],
  'SA'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'SAUDI ARABIA',
    'zip'=>'\\d{5}',
    'zipex'=>'11564,11187,11142',
  ],
  'SB'=>[
    'name'=>'SOLOMON ISLANDS',
  ],
  'SC'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'SEYCHELLES',
    'state_name_type'=>'Island',
    'upper'=>'S',
  ],
  'SE'=>[
    'fmt'=>'%O%n%N%n%A%nSE-%Z %C',
    'locality_name_type'=>'Town',
    'name'=>'SWEDEN',
    'require'=>'ACZ',
    'zip'=>'\\d{3} ?\\d{2}',
    'zipex'=>'11455,12345,10500',
  ],
  'SG'=>[
    'fmt'=>'%N%n%O%n%A%nSINGAPORE %Z',
    'name'=>'REP. OF SINGAPORE',
    'require'=>'AZ',
    'zip'=>'\\d{6}',
    'zipex'=>'546080,308125,408600',
  ],
  'SH'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SAINT HELENA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'(?:ASCN|STHL) 1ZZ',
    'zipex'=>'STHL 1ZZ',
  ],
  'SI'=>[
    'fmt'=>'%N%n%O%n%A%nSI- %Z %C',
    'name'=>'SLOVENIA',
    'zip'=>'\\d{4}',
    'zipex'=>'4000,1001,2500',
  ],
  'SJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'locality_name_type'=>'Town',
    'name'=>'SVALBARD AND JAN MAYEN ISLANDS',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'9170',
  ],
  'SK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SLOVAKIA',
    'zip'=>'\\d{3} ?\\d{2}',
    'zipex'=>'010 01,023 14,972 48,921 01,975 99',
  ],
  'SL'=>[
    'name'=>'SIERRA LEONE',
  ],
  'SM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SAN MARINO',
    'require'=>'AZ',
    'zip'=>'4789\\d',
    'zipex'=>'47890,47891,47895,47899',
  ],
  'SN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SENEGAL',
    'zip'=>'\\d{5}',
    'zipex'=>'12500,46024,16556,10000',
  ],
  'SO'=>[
    'admin_area_regex'=>'(?:(AD|Awdal|BK|BN|BR|BY|Bakool|Banaadir|Bari|Bay|GD|GG|Galguduud|Gedo|HR|Hiiraan|JD|JH|Jubbada Dhexe|Jubbada Hoose|MD|Mudug|NG|Nugaal|SD|SG|SH|SL|Sanaag|Shabeellaha Dhexe|Shabeellaha Hoose|Sool|TG|Togdheer|WG|Woqooyi Galbeed))',
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'so',
    'name'=>'SOMALIA',
    'require'=>'ACS',
    'upper'=>'ACS',
    'zip'=>'[A-Z]{2} ?\\d{5}',
    'zipex'=>'JH 09010,AD 11010',
  ],
  'SR'=>[
    'admin_area_regex'=>'(?:(Brokopondo|Commewijne|Coronie|Marowijne|Nickerie|Para|Paramaribo|Saramacca|Sipaliwini|Wanica))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'nl',
    'name'=>'SURINAME',
    'upper'=>'AS',
  ],
  'SS'=>[
    'name'=>'SOUTH SUDAN',
  ],
  'ST'=>[
    'name'=>'SAO TOME AND PRINCIPE',
  ],
  'SV'=>[
    'admin_area_regex'=>'(?:(Ahuachapan|Ahuachapán|Cabanas|Cabañas|Calatenango|Chalatenango|Cuscatlan|Cuscatlán|La Libertad|La Paz|La Union|La Unión|Morazan|Morazán|San Miguel|San Salvador|San Vicente|Santa Ana|Sonsonate|Usulutan|Usulután))',
    'fmt'=>'%N%n%O%n%A%n%Z-%C%n%S',
    'lang'=>'es',
    'name'=>'EL SALVADOR',
    'require'=>'ACS',
    'upper'=>'CSZ',
    'zip'=>'CP [1-3][1-7][0-2]\\d',
    'zipex'=>'CP 1101',
  ],
  'SX'=>[
    'name'=>'SINT MAARTEN',
  ],
  'SZ'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SWAZILAND',
    'upper'=>'ACZ',
    'zip'=>'[HLMS]\\d{3}',
    'zipex'=>'H100',
  ],
  'TA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'TRISTAN DA CUNHA',
    'zip'=>'TDCU 1ZZ',
    'zipex'=>'TDCU 1ZZ',
  ],
  'TC'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'TURKS AND CAICOS ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'TKCA 1ZZ',
    'zipex'=>'TKCA 1ZZ',
  ],
  'TD'=>[
    'name'=>'CHAD',
  ],
  'TF'=>[
    'name'=>'FRENCH SOUTHERN TERRITORIES',
  ],
  'TG'=>[
    'name'=>'TOGO',
  ],
  'TH'=>[
    'admin_area_regex'=>'(?:(กระบี่|กรุงเทพมหานคร|กาญจนบุรี|กาฬสินธุ์|กำแพงเพชร|ขอนแก่น|จังหวัด บึงกาฬ|จันทบุรี|ฉะเชิงเทรา|ชลบุรี|ชัยนาท|ชัยภูมิ|ชุมพร|ตรัง|ตราด|ตาก|นครนายก|นครปฐม|นครพนม|นครราชสีมา|นครศรีธรรมราช|นครสวรรค์|นนทบุรี|นราธิวาส|น่าน|บุรีรัมย์|ปทุมธานี|ประจวบคีรีขันธ์|ปราจีนบุรี|ปัตตานี|พระนครศรีอยุธยา|พะเยา|พังงา|พัทลุง|พิจิตร|พิษณุโลก|ภูเก็ต|มหาสารคาม|มุกดาหาร|ยะลา|ยโสธร|ระนอง|ระยอง|ราชบุรี|ร้อยเอ็ด|ลพบุรี|ลำปาง|ลำพูน|ศรีสะเกษ|สกลนคร|สงขลา|สตูล|สมุทรปราการ|สมุทรสงคราม|สมุทรสาคร|สระบุรี|สระแก้ว|สิงห์บุรี|สุพรรณบุรี|สุราษฎร์ธานี|สุรินทร์|สุโขทัย|หนองคาย|หนองบัวลำภู|อำนาจเจริญ|อุดรธานี|อุตรดิตถ์|อุทัยธานี|อุบลราชธานี|อ่างทอง|เชียงราย|เชียงใหม่|เพชรบุรี|เพชรบูรณ์|เลย|แพร่|แม่ฮ่องสอน))',
    'fmt'=>'%N%n%O%n%A%n%D %C%n%S %Z',
    'lang'=>'th',
    'name'=>'THAILAND',
    'upper'=>'S',
    'zip'=>'\\d{5}',
    'zipex'=>'10150,10210',
  ],
  'TJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TAJIKISTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'735450,734025',
  ],
  'TK'=>[
    'name'=>'TOKELAU',
  ],
  'TL'=>[
    'name'=>'TIMOR-LESTE',
  ],
  'TM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TURKMENISTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'744000',
  ],
  'TN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TUNISIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1002,8129,3100,1030',
  ],
  'TO'=>[
    'name'=>'TONGA',
  ],
  'TR'=>[
    'admin_area_regex'=>'(?:(Adana|Adıyaman|Afyon|Aksaray|Amasya|Ankara|Antalya|Ardahan|Artvin|Aydın|Ağrı|Balıkesir|Bartın|Batman|Bayburt|Bilecik|Bingöl|Bitlis|Bolu|Burdur|Bursa|Denizli|Diyarbakır|Düzce|Edirne|Elazığ|Erzincan|Erzurum|Eskişehir|Gaziantep|Giresun|Gümüşhane|Hakkari|Hatay|Isparta|Iğdır|Kahramanmaraş|Karabük|Karaman|Kars|Kastamonu|Kayseri|Kilis|Kocaeli|Konya|Kütahya|Kırklareli|Kırıkkale|Kırşehir|Malatya|Manisa|Mardin|Mersin|Muğla|Muş|Nevşehir|Niğde|Ordu|Osmaniye|Rize|Sakarya|Samsun|Siirt|Sinop|Sivas|Tekirdağ|Tokat|Trabzon|Tunceli|Uşak|Van|Yalova|Yozgat|Zonguldak|Çanakkale|Çankırı|Çorum|İstanbul|İzmir|Şanlıurfa|Şırnak))',
    'fmt'=>'%N%n%O%n%A%n%Z %C/%S',
    'lang'=>'tr',
    'locality_name_type'=>'District',
    'name'=>'TURKEY',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'01960,06101',
  ],
  'TT'=>[
    'name'=>'TRINIDAD AND TOBAGO',
  ],
  'TV'=>[
    'admin_area_regex'=>'(?:(Funafuti|Nanumanga|Nanumea|Niulakita|Niutao|Nui|Nukufetau|Nukulaelae|Vaitupu))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'tyv',
    'name'=>'TUVALU',
    'state_name_type'=>'Island',
    'upper'=>'ACS',
  ],
  'TW'=>[
    'admin_area_regex'=>'(?:(南投縣|台中市|台北市|台南市|台東縣|嘉義市|嘉義縣|基隆市|宜蘭縣|屏東縣|彰化縣|新北市|新竹市|新竹縣|桃園市|澎湖縣|花蓮縣|苗栗縣|連江縣|金門縣|雲林縣|高雄市))',
    'fmt'=>'%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'zh-Hant',
    'name'=>'TAIWAN',
    'require'=>'ACSZ',
    'state_name_type'=>'County',
    'zip'=>'\\d{3}(?:\\d{2})?',
    'zipex'=>'104,106,10603,40867',
  ],
  'TZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TANZANIA (UNITED REP.)',
    'zip'=>'\\d{4,5}',
    'zipex'=>'6090,34413',
  ],
  'UA'=>[
    'admin_area_regex'=>'(?:(Івано-Франківська область|Автономна Республіка Крим|Волинська область|Вінницька область|Дніпропетровська область|Донецька область|Житомирська область|Закарпатська область|Запорізька область|Київ|Київська область|Кіровоградська область|Луганська область|Львівська область|Миколаївська область|Одеська область|Полтавська область|Рівненська область|Севастополь|Сумська область|Тернопільська область|Харківська область|Херсонська область|Хмельницька область|Черкаська область|Чернівецька область|Чернігівська область|місто Київ|місто Севастополь))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'lang'=>'uk',
    'name'=>'UKRAINE',
    'require'=>'ACSZ',
    'state_name_type'=>'Oblast',
    'zip'=>'\\d{5}',
    'zipex'=>'15432,01055,01001',
  ],
  'UG'=>[
    'name'=>'UGANDA',
  ],
  'UM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'UNITED STATES MINOR OUTLYING ISLANDS',
    'require'=>'ACS',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'96898',
    'zip_name_type'=>'zip',
    'zipex'=>'96898',
  ],
  'US'=>[
    'org_name_type'=>'Organization',
    'locality_name_type'=>'City',
    'zip_name_type'=>'zip',
    'admin_area_regex'=>'(?:(AA|AE|AK|AL|AP|AR|AS|AZ|Alabama|Alaska|American Samoa|Arizona|Arkansas|Armed Forces (AA)|Armed Forces (AE)|Armed Forces (AP)|CA|CO|CT|California|Colorado|Connecticut|DC|DE|Delaware|District of Columbia|FL|FM|Florida|GA|GU|Georgia|Guam|HI|Hawaii|IA|ID|IL|IN|Idaho|Illinois|Indiana|Iowa|KS|KY|Kansas|Kentucky|LA|Louisiana|MA|MD|ME|MH|MI|MN|MO|MP|MS|MT|Maine|Marshall Islands|Maryland|Massachusetts|Michigan|Micronesia|Minnesota|Mississippi|Missouri|Montana|NC|ND|NE|NH|NJ|NM|NV|NY|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Northern Mariana Islands|OH|OK|OR|Ohio|Oklahoma|Oregon|PA|PR|PW|Palau|Pennsylvania|Puerto Rico|RI|Rhode Island|SC|SD|South Carolina|South Dakota|TN|TX|Tennessee|Texas|UT|Utah|VA|VI|VT|Vermont|Virgin Islands|Virginia|WA|WI|WV|WY|Washington|West Virginia|Wisconsin|Wyoming))',
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'en',
    'name'=>'UNITED STATES',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'(\\d{5})(?:[ \\-](\\d{4}))?',
    'zipex'=>'95014,22162-1010',
  ],
  'UY'=>[
    'admin_area_regex'=>'(?:(Artigas|Canelones|Cerro Largo|Colonia|Durazno|Flores|Florida|Lavalleja|Maldonado|Montevideo|Paysandú|Rivera|Rocha|Río Negro|Salto|San José|Soriano|Tacuarembó|Treinta y Tres))',
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'URUGUAY',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'11600',
  ],
  'UZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'name'=>'UZBEKISTAN',
    'upper'=>'CS',
    'zip'=>'\\d{6}',
    'zipex'=>'702100,700000',
  ],
  'VA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'VATICAN',
    'zip'=>'00120',
    'zipex'=>'00120',
  ],
  'VC'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'SAINT VINCENT AND THE GRENADINES (ANTILLES)',
    'zip'=>'VC\\d{4}',
    'zipex'=>'VC0100,VC0110,VC0400',
  ],
  'VE'=>[
    'admin_area_regex'=>'(?:(Amazonas|Anzoátegui|Apure|Aragua|Barinas|Bolívar|Carabobo|Cojedes|Delta Amacuro|Dependencias Federales|Distrito Federal|Falcón|Guárico|Lara|Miranda|Monagas|Mérida|Nueva Esparta|Portuguesa|Sucre|Trujillo|Táchira|Vargas|Yaracuy|Zulia))',
    'fmt'=>'%N%n%O%n%A%n%C %Z, %S',
    'lang'=>'es',
    'name'=>'VENEZUELA',
    'require'=>'ACS',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
    'zipex'=>'1010,3001,8011,1020',
  ],
  'VG'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'VIRGIN ISLANDS (BRITISH)',
    'require'=>'A',
    'zip'=>'VG\\d{4}',
    'zipex'=>'VG1110,VG1150,VG1160',
  ],
  'VI'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'VIRGIN ISLANDS (U.S.)',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?',
    'zip_name_type'=>'zip',
    'zipex'=>'00802-1222,00850-9802',
  ],
  'VN'=>[
    'admin_area_regex'=>'(?:(An Giang|Bà Rịa–Vũng Tàu|Bình Dương|Bình Phước|Bình Thuận|Bình Định|Bạc Liêu|Bắc Giang|Bắc Kạn|Bắc Ninh|Bến Tre|Cao Bằng|Cà Mau|Cần Thơ|Gia Lai|Hà Giang|Hà Nam|Hà Nội|Hà Tĩnh|Hòa Bình|Hưng Yên|Hải Dương|Hải Phòng|Hậu Giang|Khánh Hòa|Kiên Giang|Kon Tum|Lai Châu|Long An|Lào Cai|Lâm Đồng|Lạng Sơn|Nam Định|Nghệ An|Ninh Bình|Ninh Thuận|Phú Thọ|Phú Yên|Quảng Bình|Quảng Nam|Quảng Ngãi|Quảng Ninh|Quảng Trị|Sóc Trăng|Sơn La|Thanh Hóa|Thành phố Hồ Chí Minh|Thái Bình|Thái Nguyên|Thừa Thiên–Huế|Tiền Giang|Trà Vinh|Tuyên Quang|Tây Ninh|Vĩnh Long|Vĩnh Phúc|Yên Bái|Điện Biên|Đà Nẵng|Đăk Nông|Đắk Lắk|Đồng Nai|Đồng Tháp))',
    'fmt'=>'%N%n%O%n%A%n%C%n%S %Z',
    'lang'=>'vi',
    'name'=>'VIET NAM',
    'zip'=>'\\d{6}',
    'zipex'=>'119415,136065,720344',
  ],
  'VU'=>[
    'name'=>'VANUATU',
  ],
  'WF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'WALLIS AND FUTUNA ISLANDS',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'986\\d{2}',
    'zipex'=>'98600',
  ],
  'WS'=>[
    'name'=>'SAMOA',
  ],
  'XK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KOSOVO',
    'zip'=>'[1-7]\\d{4}',
    'zipex'=>'10000',
  ],
  'YE'=>[
    'name'=>'YEMEN',
  ],
  'YT'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MAYOTTE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'976\\d{2}',
    'zipex'=>'97600',
  ],
  'YU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
    'zipex'=>'11001',
  ],
  'ZA'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C%n%Z',
    'name'=>'SOUTH AFRICA',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'0083,1451,0001',
  ],
  'ZM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ZAMBIA',
    'zip'=>'\\d{5}',
    'zipex'=>'50100,50101',
  ],
  'ZW'=>[
    'name'=>'ZIMBABWE',
  ],
];
