<?php

return [
  'AC'=>[
    'name'=>'ASCENSION ISLAND',
    'zip'=>'ASCN 1ZZ',
  ],
  'AD'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %S',
    'lang'=>'ca',
    'name'=>'ANDORRA',
    'require'=>'AS',
    'state_name_type'=>'Parish',
    'upper'=>'S',
    'zip'=>'AD[1-7]0\\d',
  ],
  'AE'=>[
    'fmt'=>'%N%n%O%n%A%n%C',
    'name'=>'UNITED ARAB EMIRATES',
    'require'=>'AC',
  ],
  'AF'=>[
    'name'=>'AFGHANISTAN',
    'zip'=>'\\d{4}',
  ],
  'AG'=>[
    'name'=>'ANTIGUA AND BARBUDA',
    'require'=>'A',
  ],
  'AI'=>[
    'name'=>'ANGUILLA',
    'zip'=>'2640',
  ],
  'AL'=>[
    'name'=>'ALBANIA',
    'zip'=>'\\d{4}',
  ],
  'AM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C%n%S',
    'lang'=>'hy',
    'name'=>'ARMENIA',
    'zip'=>'(37)?\\d{4}',
  ],
  'AN'=>[
    'name'=>'NETHERLANDS ANTILLES',
  ],
  'AO'=>[
    'name'=>'ANGOLA',
  ],
  'AQ'=>[
    'name'=>'ANTARCTICA',
  ],
  'AR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'ARGENTINA',
    'state_name_type'=>'State',
    'upper'=>'ACZ',
    'zip'=>'((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?',
  ],
  'AS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'AMERICAN SAMOA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(96799)(?:[ \\-](\\d{4}))?',
  ],
  'AT'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'AUSTRIA',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'AU'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'lang'=>'en',
    'name'=>'AUSTRALIA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
  ],
  'AW'=>[
    'name'=>'ARUBA',
  ],
  'AX'=>[
    'fmt'=>'%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    'name'=>'FINLAND',
    'require'=>'ACZ',
    'zip'=>'22\\d{3}',
  ],
  'AZ'=>[
    'fmt'=>'%N%n%O%n%A%nAZ %Z %C',
    'name'=>'AZERBAIJAN',
    'zip'=>'\\d{4}',
  ],
  'BA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BOSNIA AND HERZEGOVINA',
    'zip'=>'\\d{5}',
  ],
  'BB'=>[
    'name'=>'BARBADOS',
    'state_name_type'=>'Parish',
    'zip'=>'(?:BB\\d{5})?',
  ],
  'BD'=>[
    'fmt'=>'%N%n%O%n%A%n%C - %Z',
    'name'=>'BANGLADESH',
    'zip'=>'\\d{4}',
  ],
  'BE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'BELGIUM',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'BF'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'BURKINA FASO',
  ],
  'BG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BULGARIA (REP.)',
    'zip'=>'\\d{4}',
  ],
  'BH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BAHRAIN',
    'zip'=>'(?:(?:\\d|1[0-2])\\d{2})?',
  ],
  'BI'=>[
    'name'=>'BURUNDI',
  ],
  'BJ'=>[
    'name'=>'BENIN',
    'upper'=>'AC',
  ],
  'BL'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT BARTHELEMY',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
  ],
  'BM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BERMUDA',
    'zip'=>'[A-Z]{2}[ ]?[A-Z0-9]{2}',
  ],
  'BN'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BRUNEI DARUSSALAM',
    'zip'=>'[A-Z]{2}[ ]?\\d{4}',
  ],
  'BO'=>[
    'name'=>'BOLIVIA',
    'upper'=>'AC',
  ],
  'BR'=>[
    'fmt'=>'%O%n%N%n%A%n%C-%S%n%Z',
    'lang'=>'pt',
    'name'=>'BRAZIL',
    'require'=>'ASCZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}[\\-]?\\d{3}',
  ],
  'BS'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'BAHAMAS',
    'state_name_type'=>'Island',
  ],
  'BT'=>[
    'name'=>'BHUTAN',
    'zip'=>'\\d{5}',
  ],
  'BV'=>[
    'name'=>'BOUVET ISLAND',
  ],
  'BW'=>[
    'name'=>'BOTSWANA',
  ],
  'BY'=>[
    'fmt'=>'%S%n%Z %C %X%n%A%n%O%n%N',
    'name'=>'BELARUS',
    'zip'=>'\\d{6}',
  ],
  'BZ'=>[
    'name'=>'BELIZE',
  ],
  'CA'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'lang'=>'en',
    'name'=>'CANADA',
    'require'=>'ACSZ',
    'upper'=>'ACNOSZ',
    'zip'=>'[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d',
  ],
  'CC'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'COCOS (KEELING) ISLANDS',
    'upper'=>'CS',
    'zip'=>'6799',
  ],
  'CD'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'CONGO (DEM. REP.)',
  ],
  'CF'=>[
    'name'=>'CENTRAL AFRICAN REPUBLIC',
  ],
  'CG'=>[
    'name'=>'CONGO (REP.)',
  ],
  'CH'=>[
    'fmt'=>'%O%n%N%n%A%nCH-%Z %C',
    'lang'=>'de',
    'name'=>'SWITZERLAND',
    'require'=>'ACZ',
    'upper'=>'',
    'zip'=>'\\d{4}',
  ],
  'CI'=>[
    'fmt'=>'%N%n%O%n%X %A %C %X',
    'name'=>'COTE D\'IVOIRE',
  ],
  'CK'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'COOK ISLANDS',
    'zip'=>'\\d{4}',
  ],
  'CL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'CHILE',
    'state_name_type'=>'State',
    'zip'=>'\\d{7}',
  ],
  'CM'=>[
    'name'=>'CAMEROON',
  ],
  'CN'=>[
    'fmt'=>'%Z%n%S%C%D%n%A%n%O%n%N',
    'lang'=>'zh-hans',
    'name'=>'P.R. CHINA',
    'require'=>'ACSZ',
    'upper'=>'S',
    'zip'=>'\\d{6}',
  ],
  'CO'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'name'=>'COLOMBIA',
    'zip'=>'\\d{6}',
  ],
  'CR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'COSTA RICA',
    'zip'=>'\\d{4,5}|\\d{3}-\\d{4}',
  ],
  'CS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
  ],
  'CV'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'pt',
    'name'=>'CAPE VERDE',
    'state_name_type'=>'Island',
    'zip'=>'\\d{4}',
  ],
  'CX'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'CHRISTMAS ISLAND',
    'upper'=>'CS',
    'zip'=>'6798',
  ],
  'CY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CYPRUS',
    'zip'=>'\\d{4}',
  ],
  'CZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CZECH REP.',
    'zip'=>'\\d{3}[ ]?\\d{2}',
  ],
  'DE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GERMANY',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
  ],
  'DJ'=>[
    'name'=>'DJIBOUTI',
  ],
  'DK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DENMARK',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'DM'=>[
    'name'=>'DOMINICA',
  ],
  'DO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DOMINICAN REP.',
    'zip'=>'\\d{5}',
  ],
  'DZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ALGERIA',
    'zip'=>'\\d{5}',
  ],
  'EC'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'ECUADOR',
    'upper'=>'CZ',
    'zip'=>'(?:[A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?',
  ],
  'EE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ESTONIA',
    'zip'=>'\\d{5}',
  ],
  'EG'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'lang'=>'ar',
    'name'=>'EGYPT',
    'zip'=>'\\d{5}',
  ],
  'EH'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'WESTERN SAHARA',
    'zip'=>'\\d{5}',
  ],
  'ER'=>[
    'name'=>'ERITREA',
  ],
  'ES'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'SPAIN',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'ET'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ETHIOPIA',
    'zip'=>'\\d{4}',
  ],
  'FI'=>[
    'fmt'=>'%O%n%N%n%A%nFI-%Z %C',
    'name'=>'FINLAND',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
  ],
  'FJ'=>[
    'name'=>'FIJI',
  ],
  'FK'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'FALKLAND ISLANDS (MALVINAS)',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'FIQQ 1ZZ',
  ],
  'FM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MICRONESIA (Federated State of)',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9694[1-4])(?:[ \\-](\\d{4}))?',
  ],
  'FO'=>[
    'fmt'=>'%N%n%O%n%A%nFO%Z %C',
    'name'=>'FAROE ISLANDS',
    'zip'=>'\\d{3}',
  ],
  'FR'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRANCE',
    'require'=>'ACZ',
    'upper'=>'CX',
    'zip'=>'\\d{2}[ ]?\\d{3}',
  ],
  'GA'=>[
    'name'=>'GABON',
  ],
  'GB'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'locality_name_type'=>'Town',
    'name'=>'UNITED KINGDOM',
    'require'=>'ACZ',
    'state_name_type'=>'County',
    'upper'=>'CZ',
    'zip'=>'GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}',
  ],
  'GD'=>[
    'name'=>'GRENADA (WEST INDIES)',
  ],
  'GE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GEORGIA',
    'zip'=>'\\d{4}',
  ],
  'GF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRENCH GUIANA',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]3\\d{2}',
  ],
  'GG'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%nGUERNSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
  ],
  'GH'=>[
    'name'=>'GHANA',
  ],
  'GI'=>[
    'fmt'=>'%N%n%O%n%A',
    'name'=>'GIBRALTAR',
    'require'=>'A',
    'zip'=>'GX11 1AA',
  ],
  'GL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREENLAND',
    'require'=>'ACZ',
    'zip'=>'39\\d{2}',
  ],
  'GM'=>[
    'name'=>'GAMBIA',
  ],
  'GN'=>[
    'fmt'=>'%N%n%O%n%Z %A %C',
    'name'=>'GUINEA',
    'zip'=>'\\d{3}',
  ],
  'GP'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'GUADELOUPE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
  ],
  'GQ'=>[
    'name'=>'EQUATORIAL GUINEA',
  ],
  'GR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREECE',
    'require'=>'ACZ',
    'zip'=>'\\d{3} ?\\d{2}',
  ],
  'GS'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'SOUTH GEORGIA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'SIQQ 1ZZ',
  ],
  'GT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z- %C',
    'name'=>'GUATEMALA',
    'zip'=>'\\d{5}',
  ],
  'GU'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'GUAM',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
  ],
  'GW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GUINEA-BISSAU',
    'zip'=>'\\d{4}',
  ],
  'GY'=>[
    'name'=>'GUYANA',
  ],
  'HK'=>[
    'fmt'=>'%S%n%A%n%O%n%N',
    'lang'=>'zh-hant',
    'name'=>'HONG KONG',
    'require'=>'AS',
    'state_name_type'=>'Area',
    'upper'=>'S',
  ],
  'HM'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'HEARD AND MCDONALD ISLANDS',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
  ],
  'HN'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S%n%Z',
    'name'=>'HONDURAS',
    'require'=>'ACS',
    'zip'=>'(?:\\d{5})?',
  ],
  'HR'=>[
    'fmt'=>'%N%n%O%n%A%nHR-%Z %C',
    'name'=>'CROATIA',
    'zip'=>'\\d{5}',
  ],
  'HT'=>[
    'fmt'=>'%N%n%O%n%A%nHT%Z %C %X',
    'name'=>'HAITI',
    'zip'=>'\\d{4}',
  ],
  'HU'=>[
    'fmt'=>'%N%n%O%n%C%n%A%n%Z',
    'name'=>'HUNGARY (Rep.)',
    'upper'=>'ACNO',
    'zip'=>'\\d{4}',
  ],
  'ID'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S %Z',
    'lang'=>'id',
    'name'=>'INDONESIA',
    'state_name_type'=>'District',
    'zip'=>'\\d{5}',
  ],
  'IE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'en',
    'name'=>'IRELAND',
    'state_name_type'=>'County',
  ],
  'IL'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'ISRAEL',
    'zip'=>'\\d{5}(?:\\d{2})?',
  ],
  'IM'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'ISLE OF MAN',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
  ],
  'IN'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'INDIA',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'zip'=>'\\d{6}',
  ],
  'IO'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'BRITISH INDIAN OCEAN TERRITORY',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'BBND 1ZZ',
  ],
  'IQ'=>[
    'fmt'=>'%O%n%N%n%A%n%C, %S%n%Z',
    'name'=>'IRAQ',
    'require'=>'ACS',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'IS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ICELAND',
    'zip'=>'\\d{3}',
  ],
  'IT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'it',
    'name'=>'ITALY',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'JE'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%nJERSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
  ],
  'JM'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S %X',
    'lang'=>'en',
    'name'=>'JAMAICA',
    'require'=>'ACS',
    'state_name_type'=>'Parish',
  ],
  'JO'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'JORDAN',
    'zip'=>'\\d{5}',
  ],
  'JP'=>[
    'fmt'=>'〒%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'ja',
    'name'=>'JAPAN',
    'require'=>'ACSZ',
    'state_name_type'=>'Prefecture',
    'upper'=>'S',
    'zip'=>'\\d{3}-?\\d{4}',
  ],
  'KE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'KENYA',
    'zip'=>'\\d{5}',
  ],
  'KG'=>[
    'fmt'=>'%Z %C %X%n%A%n%O%n%N',
    'name'=>'KYRGYZSTAN',
    'zip'=>'\\d{6}',
  ],
  'KH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'CAMBODIA',
    'zip'=>'\\d{5}',
  ],
  'KI'=>[
    'fmt'=>'%N%n%O%n%A%n%S%n%C',
    'name'=>'KIRIBATI',
    'state_name_type'=>'Island',
    'upper'=>'ACNOS',
  ],
  'KM'=>[
    'name'=>'COMOROS',
    'upper'=>'AC',
  ],
  'KN'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'SAINT KITTS AND NEVIS',
    'require'=>'ACS',
    'state_name_type'=>'Island',
  ],
  'KR'=>[
    'fmt'=>'%S %C%D%n%A%n%O%n%N%n%Z',
    'lang'=>'ko',
    'name'=>'KOREA (REP.)',
    'require'=>'ACSZ',
    'state_name_type'=>'Do Si',
    'upper'=>'Z',
    'zip'=>'\\d{3}[\\-]\\d{3}',
  ],
  'KW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KUWAIT',
    'zip'=>'\\d{5}',
  ],
  'KY'=>[
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'en',
    'name'=>'CAYMAN ISLANDS',
    'require'=>'AS',
    'state_name_type'=>'Island',
    'zip'=>'KY\\d-\\d{4}',
  ],
  'KZ'=>[
    'fmt'=>'%Z%n%S%n%C%n%A%n%O%n%N',
    'name'=>'KAZAKHSTAN',
    'zip'=>'\\d{6}',
  ],
  'LA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'LAO (PEOPLE\'S DEM. REP.)',
    'zip'=>'\\d{5}',
  ],
  'LB'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LEBANON',
    'zip'=>'(?:(?:\\d{4})(?:[ ]?(?:\\d{4}))?)?',
  ],
  'LC'=>[
    'name'=>'SAINT LUCIA',
  ],
  'LI'=>[
    'fmt'=>'%O%n%N%n%A%nFL-%Z %C',
    'name'=>'LIECHTENSTEIN',
    'require'=>'ACZ',
    'zip'=>'(948[5-9])|(949[0-7])',
  ],
  'LK'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SRI LANKA',
    'zip'=>'\\d{5}',
  ],
  'LR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %X',
    'name'=>'LIBERIA',
    'zip'=>'\\d{4}',
  ],
  'LS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LESOTHO',
    'zip'=>'\\d{3}',
  ],
  'LT'=>[
    'fmt'=>'%O%n%N%n%A%nLT-%Z %C',
    'name'=>'LITHUANIA',
    'zip'=>'\\d{5}',
  ],
  'LU'=>[
    'fmt'=>'%O%n%N%n%A%nL-%Z %C',
    'name'=>'LUXEMBOURG',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'LV'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %Z',
    'name'=>'LATVIA',
    'zip'=>'LV-\\d{4}',
  ],
  'LY'=>[
    'name'=>'LIBYA',
  ],
  'MA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MOROCCO',
    'zip'=>'\\d{5}',
  ],
  'MC'=>[
    'fmt'=>'%N%n%O%n%A%nMC-%Z %C %X',
    'name'=>'MONACO',
    'zip'=>'980\\d{2}',
  ],
  'MD'=>[
    'fmt'=>'%N%n%O%n%A%nMD-%Z %C',
    'name'=>'Rep. MOLDOVA',
    'zip'=>'\\d{4}',
  ],
  'ME'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MONTENEGRO',
    'zip'=>'8\\d{4}',
  ],
  'MF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT MARTIN',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
  ],
  'MG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MADAGASCAR',
    'zip'=>'\\d{3}',
  ],
  'MH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MARSHALL ISLANDS',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969[67]\\d)(?:[ \\-](\\d{4}))?',
  ],
  'MK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MACEDONIA',
    'zip'=>'\\d{4}',
  ],
  'ML'=>[
    'name'=>'MALI',
  ],
  'MN'=>[
    'fmt'=>'%N%n%O%n%A%n%S %C-%X%n%Z',
    'name'=>'MONGOLIA',
    'zip'=>'\\d{5}',
  ],
  'MO'=>[
    'fmt'=>'%A%n%O%n%N',
    'name'=>'MACAO',
    'require'=>'A',
  ],
  'MP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'NORTHERN MARIANA ISLANDS',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9695[012])(?:[ \\-](\\d{4}))?',
  ],
  'MQ'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MARTINIQUE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]2\\d{2}',
  ],
  'MR'=>[
    'name'=>'MAURITANIA',
    'upper'=>'AC',
  ],
  'MS'=>[
    'name'=>'MONTSERRAT',
  ],
  'MT'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALTA',
    'upper'=>'CZ',
    'zip'=>'[A-Z]{3}[ ]?\\d{2,4}',
  ],
  'MU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'MAURITIUS',
    'upper'=>'CZ',
    'zip'=>'(?:\\d{3}[A-Z]{2}\\d{3})?',
  ],
  'MV'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALDIVES',
    'zip'=>'\\d{5}',
  ],
  'MW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'MALAWI',
  ],
  'MX'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C, %S',
    'lang'=>'es',
    'name'=>'MEXICO',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CSZ',
    'zip'=>'\\d{5}',
  ],
  'MY'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C%n%S',
    'lang'=>'ms',
    'name'=>'MALAYSIA',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'MZ'=>[
    'fmt'=>'%N%n%O%n%A%n%C',
    'name'=>'MOZAMBIQUE',
    'zip'=>'\\d{4}',
  ],
  'NA'=>[
    'name'=>'NAMIBIA',
  ],
  'NC'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'NEW CALEDONIA',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'988\\d{2}',
  ],
  'NE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'NIGER',
    'zip'=>'\\d{4}',
  ],
  'NF'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'NORFOLK ISLAND',
    'upper'=>'CS',
    'zip'=>'2899',
  ],
  'NG'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'NIGERIA',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'(?:\\d{6})?',
  ],
  'NI'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C, %S',
    'lang'=>'es',
    'name'=>'NICARAGUA',
    'state_name_type'=>'Department',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'NL'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'NETHERLANDS',
    'require'=>'ACZ',
    'zip'=>'\\d{4}[ ]?[A-Z]{2}',
  ],
  'NO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'NORWAY',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'NP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'NEPAL',
    'zip'=>'\\d{5}',
  ],
  'NR'=>[
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'en',
    'name'=>'NAURU CENTRAL PACIFIC',
    'require'=>'AS',
    'state_name_type'=>'District',
  ],
  'NU'=>[
    'name'=>'NIUE',
  ],
  'NZ'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C %Z',
    'name'=>'NEW ZEALAND',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'OM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'OMAN',
    'zip'=>'(PC )?\\d{3}',
  ],
  'PA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'PANAMA (REP.)',
    'upper'=>'CS',
  ],
  'PE'=>[
    'name'=>'PERU',
    'zip'=>'(?:LIMA \\d|CALLAO 0?)\\d|[0-2]\\d{4}',
  ],
  'PF'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'name'=>'FRENCH POLYNESIA',
    'require'=>'ACSZ',
    'state_name_type'=>'Island',
    'upper'=>'CS',
    'zip'=>'987\\d{2}',
  ],
  'PG'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z %S',
    'name'=>'PAPUA NEW GUINEA',
    'require'=>'ACS',
    'zip'=>'\\d{3}',
  ],
  'PH'=>[
    'fmt'=>'%N%n%O%n%A%n%D, %C%n%Z %S',
    'lang'=>'en',
    'name'=>'PHILIPPINES',
    'zip'=>'\\d{4}',
  ],
  'PK'=>[
    'fmt'=>'%N%n%O%n%A%n%C-%Z',
    'name'=>'PAKISTAN',
    'zip'=>'\\d{5}',
  ],
  'PL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'POLAND',
    'require'=>'ACZ',
    'zip'=>'\\d{2}-\\d{3}',
  ],
  'PM'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'ST. PIERRE AND MIQUELON',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]5\\d{2}',
  ],
  'PN'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'PITCAIRN',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'PCRN 1ZZ',
  ],
  'PR'=>[
    'fmt'=>'%N%n%O%n%A%n%C PR %Z',
    'name'=>'PUERTO RICO',
    'require'=>'ACZ',
    'upper'=>'ACNO',
    'zip'=>'(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
  ],
  'PS'=>[
    'name'=>'PALESTINIAN TERRITORY',
  ],
  'PT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PORTUGAL',
    'require'=>'ACZ',
    'zip'=>'\\d{4}-\\d{3}',
  ],
  'PW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'PALAU',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:39|40))(?:[ \\-](\\d{4}))?',
  ],
  'PY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PARAGUAY',
    'zip'=>'\\d{4}',
  ],
  'QA'=>[
    'name'=>'QATAR',
    'upper'=>'AC',
  ],
  'RE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'REUNION',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]4\\d{2}',
  ],
  'RO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ROMANIA',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
  ],
  'RS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'REPUBLIC OF SERBIA',
    'zip'=>'\\d{5,6}',
  ],
  'RU'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'name'=>'RUSSIAN FEDERATION',
    'require'=>'ACZ',
    'state_name_type'=>'Oblast',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
  ],
  'RW'=>[
    'name'=>'RWANDA',
    'upper'=>'AC',
  ],
  'SA'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'SAUDI ARABIA',
    'zip'=>'\\d{5}',
  ],
  'SB'=>[
    'name'=>'SOLOMON ISLANDS',
  ],
  'SC'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'SEYCHELLES',
    'state_name_type'=>'Island',
    'upper'=>'S',
  ],
  'SE'=>[
    'fmt'=>'%O%n%N%n%A%nSE-%Z %C',
    'name'=>'SWEDEN',
    'require'=>'ACZ',
    'zip'=>'\\d{3}[ ]?\\d{2}',
  ],
  'SG'=>[
    'fmt'=>'%N%n%O%n%A%nSINGAPORE %Z',
    'name'=>'REP. OF SINGAPORE',
    'require'=>'AZ',
    'zip'=>'\\d{6}',
  ],
  'SH'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'SAINT HELENA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'(ASCN|STHL) 1ZZ',
  ],
  'SI'=>[
    'fmt'=>'%N%n%O%n%A%nSI- %Z %C',
    'name'=>'SLOVENIA',
    'zip'=>'\\d{4}',
  ],
  'SJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SVALBARD AND JAN MAYEN ISLANDS',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'SK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SLOVAKIA',
    'zip'=>'\\d{3}[ ]?\\d{2}',
  ],
  'SL'=>[
    'name'=>'SIERRA LEONE',
  ],
  'SM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SAN MARINO',
    'require'=>'AZ',
    'zip'=>'4789\\d',
  ],
  'SN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SENEGAL',
    'zip'=>'\\d{5}',
  ],
  'SO'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'so',
    'name'=>'SOMALIA',
    'require'=>'ACS',
    'upper'=>'ACS',
    'zip'=>'\\d{5}',
  ],
  'SR'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X%n%S',
    'lang'=>'nl',
    'name'=>'SURINAME',
    'upper'=>'AS',
  ],
  'ST'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'SAO TOME AND PRINCIPE',
  ],
  'SV'=>[
    'fmt'=>'%N%n%O%n%A%n%Z-%C%n%S',
    'lang'=>'es',
    'name'=>'EL SALVADOR',
    'require'=>'ACS',
    'upper'=>'CSZ',
    'zip'=>'CP [1-3][1-7][0-2]\\d',
  ],
  'SZ'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SWAZILAND',
    'upper'=>'ACZ',
    'zip'=>'[HLMS]\\d{3}',
  ],
  'TA'=>[
    'name'=>'TRISTAN DA CUNHA',
    'zip'=>'TDCU 1ZZ',
  ],
  'TC'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'TURKS AND CAICOS ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'TKCA 1ZZ',
  ],
  'TD'=>[
    'name'=>'CHAD',
  ],
  'TF'=>[
    'name'=>'FRENCH SOUTHERN TERRITORIES',
  ],
  'TG'=>[
    'name'=>'TOGO',
  ],
  'TH'=>[
    'fmt'=>'%N%n%O%n%A%n%D %C%n%S %Z',
    'lang'=>'th',
    'name'=>'THAILAND',
    'upper'=>'S',
    'zip'=>'\\d{5}',
  ],
  'TJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TAJIKISTAN',
    'zip'=>'\\d{6}',
  ],
  'TK'=>[
    'name'=>'TOKELAU',
  ],
  'TL'=>[
    'name'=>'TIMOR-LESTE',
  ],
  'TM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TURKMENISTAN',
    'zip'=>'\\d{6}',
  ],
  'TN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TUNISIA',
    'zip'=>'\\d{4}',
  ],
  'TO'=>[
    'name'=>'TONGA',
  ],
  'TR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C/%S',
    'lang'=>'tr',
    'locality_name_type'=>'District',
    'name'=>'TURKEY',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
  ],
  'TT'=>[
    'name'=>'TRINIDAD AND TOBAGO',
  ],
  'TV'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%S',
    'lang'=>'tyv',
    'name'=>'TUVALU',
    'state_name_type'=>'Island',
    'upper'=>'ACS',
  ],
  'TW'=>[
    'fmt'=>'%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'zh-hant',
    'name'=>'TAIWAN',
    'require'=>'ACSZ',
    'state_name_type'=>'County',
    'zip'=>'\\d{3}(\\d{2})?',
  ],
  'TZ'=>[
    'name'=>'TANZANIA (UNITED REP.)',
    'zip'=>'\\d{4}',
  ],
  'UA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'name'=>'UKRAINE',
    'require'=>'ACZ',
    'state_name_type'=>'Oblast',
    'zip'=>'\\d{5}',
  ],
  'UG'=>[
    'name'=>'UGANDA',
  ],
  'UM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'UNITED STATES MINOR OUTLYING ISLANDS',
    'require'=>'ACS',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'96898',
  ],
  'US'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'en',
    'name'=>'UNITED STATES',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'(\\d{5})(?:[ \\-](\\d{4}))?',
  ],
  'UY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'URUGUAY',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'UZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'name'=>'UZBEKISTAN',
    'upper'=>'CS',
    'zip'=>'\\d{6}',
  ],
  'VA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'VATICAN',
    'zip'=>'00120',
  ],
  'VC'=>[
    'name'=>'SAINT VINCENT AND THE GRENADINES (ANTILLES)',
    'zip'=>'VC\\d{4}',
  ],
  'VE'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z, %S',
    'lang'=>'es',
    'name'=>'VENEZUELA',
    'require'=>'ACS',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
  ],
  'VG'=>[
    'name'=>'VIRGIN ISLANDS (BRITISH)',
    'require'=>'A',
    'zip'=>'VG\\d{4}',
  ],
  'VI'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'VIRGIN ISLANDS (U.S.)',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?',
  ],
  'VN'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'vi',
    'name'=>'VIET NAM',
    'require'=>'AC',
    'zip'=>'\\d{6}',
  ],
  'VU'=>[
    'name'=>'VANUATU',
  ],
  'WF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'WALLIS AND FUTUNA ISLANDS',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'986\\d{2}',
  ],
  'WS'=>[
    'name'=>'SAMOA',
  ],
  'XK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KOSOVO',
    'zip'=>'[1-7]\\d{4}',
  ],
  'YE'=>[
    'name'=>'YEMEN',
    'require'=>'AC',
  ],
  'YT'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MAYOTTE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'976\\d{2}',
  ],
  'YU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
  ],
  'ZA'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C%n%Z',
    'name'=>'SOUTH AFRICA',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
  ],
  'ZM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ZAMBIA',
    'require'=>'AC',
    'zip'=>'\\d{5}',
  ],
  'ZW'=>[
    'name'=>'ZIMBABWE',
  ],
];