<?php

return [
  'AC'=>[
    'name'=>'ASCENSION ISLAND',
    'zip'=>'ASCN 1ZZ',
    'zipex'=>'ASCN 1ZZ',
  ],
  'AD'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %S',
    'lang'=>'ca',
    'name'=>'ANDORRA',
    'posturl'=>'http://www.correos.es/comun/CodigosPostales/1010_s-CodPostal.asp?Provincia=',
    'require'=>'AS',
    'state_name_type'=>'Parish',
    'upper'=>'S',
    'zip'=>'AD[1-7]0\\d',
    'zipex'=>'AD100,AD501,AD700',
  ],
  'AE'=>[
    'fmt'=>'%N%n%O%n%A%n%C',
    'name'=>'UNITED ARAB EMIRATES',
    'require'=>'AC',
  ],
  'AF'=>[
    'name'=>'AFGHANISTAN',
    'posturl'=>'http://afghanpost.gov.af/Postal%20Code/',
    'zip'=>'\\d{4}',
    'zipex'=>'1001,2601,3801',
  ],
  'AG'=>[
    'name'=>'ANTIGUA AND BARBUDA',
    'require'=>'A',
  ],
  'AI'=>[
    'name'=>'ANGUILLA',
    'zip'=>'2640',
    'zipex'=>'2640',
  ],
  'AL'=>[
    'name'=>'ALBANIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1001,1017,3501',
  ],
  'AM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C%n%S',
    'lang'=>'hy',
    'name'=>'ARMENIA',
    'zip'=>'(37)?\\d{4}',
    'zipex'=>'375010,0002,0010',
  ],
  'AN'=>[
    'name'=>'NETHERLANDS ANTILLES',
  ],
  'AO'=>[
    'name'=>'ANGOLA',
  ],
  'AQ'=>[
    'name'=>'ANTARCTICA',
  ],
  'AR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'ARGENTINA',
    'posturl'=>'http://www.correoargentino.com.ar/formularios/cpa',
    'state_name_type'=>'State',
    'upper'=>'ACZ',
    'zip'=>'((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?',
    'zipex'=>'C1070AAM,C1000WAM,B1000TBU,X5187XAB',
  ],
  'AS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'AMERICAN SAMOA',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(96799)(?:[ \\-](\\d{4}))?',
    'zipex'=>'96799',
  ],
  'AT'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'AUSTRIA',
    'posturl'=>'http://www.post.at/post_subsite_postleitzahlfinder.php',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'1010,3741',
  ],
  'AU'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'lang'=>'en',
    'name'=>'AUSTRALIA',
    'posturl'=>'http://www1.auspost.com.au/postcodes/',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
    'zipex'=>'2060,3171,6430,4000,4006,3001',
  ],
  'AW'=>[
    'name'=>'ARUBA',
  ],
  'AX'=>[
    'fmt'=>'%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    'name'=>'FINLAND',
    'posturl'=>'http://www.posten.ax/department.con?iPage=123',
    'require'=>'ACZ',
    'zip'=>'22\\d{3}',
    'zipex'=>'22150,22550,22240,22710,22270,22730,22430',
  ],
  'AZ'=>[
    'fmt'=>'%N%n%O%n%A%nAZ %Z %C',
    'name'=>'AZERBAIJAN',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'BA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BOSNIA AND HERZEGOVINA',
    'posturl'=>'http://www.post.ba/postanski_brojevi.php',
    'zip'=>'\\d{5}',
    'zipex'=>'71000',
  ],
  'BB'=>[
    'name'=>'BARBADOS',
    'posturl'=>'http://barbadospostal.com/zipcodes.html',
    'state_name_type'=>'Parish',
    'zip'=>'(?:BB\\d{5})?',
    'zipex'=>'BB23026,BB22025',
  ],
  'BD'=>[
    'fmt'=>'%N%n%O%n%A%n%C - %Z',
    'name'=>'BANGLADESH',
    'posturl'=>'http://www.bangladeshpost.gov.bd/PostCode.asp',
    'zip'=>'\\d{4}',
    'zipex'=>'1340,1000',
  ],
  'BE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'BELGIUM',
    'posturl'=>'http://www.post.be/site/nl/residential/customerservice/search/postal_codes.html',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'4000,1000',
  ],
  'BF'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'BURKINA FASO',
  ],
  'BG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'BULGARIA (REP.)',
    'posturl'=>'http://www.bgpost.bg/?cid=5',
    'zip'=>'\\d{4}',
    'zipex'=>'1000,1700',
  ],
  'BH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BAHRAIN',
    'zip'=>'(?:(?:\\d|1[0-2])\\d{2})?',
    'zipex'=>'317',
  ],
  'BI'=>[
    'name'=>'BURUNDI',
  ],
  'BJ'=>[
    'name'=>'BENIN',
    'upper'=>'AC',
  ],
  'BL'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT BARTHELEMY',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'BM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BERMUDA',
    'posturl'=>'http://www.landvaluation.bm/',
    'zip'=>'[A-Z]{2}[ ]?[A-Z0-9]{2}',
    'zipex'=>'FL 07,HM GX,HM 12',
  ],
  'BN'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'BRUNEI DARUSSALAM',
    'posturl'=>'http://www.post.gov.bn/index.php/extensions/postcode-guide',
    'zip'=>'[A-Z]{2}[ ]?\\d{4}',
    'zipex'=>'BT2328,KA1131,BA1511',
  ],
  'BO'=>[
    'name'=>'BOLIVIA',
    'upper'=>'AC',
  ],
  'BR'=>[
    'fmt'=>'%O%n%N%n%A%n%C-%S%n%Z',
    'lang'=>'pt',
    'name'=>'BRAZIL',
    'posturl'=>'http://www.correios.com.br/servicos/cep/cep_default.cfm',
    'require'=>'ASCZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}[\\-]?\\d{3}',
    'zipex'=>'40301-110,70002-900',
  ],
  'BS'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'BAHAMAS',
    'state_name_type'=>'Island',
  ],
  'BT'=>[
    'name'=>'BHUTAN',
    'posturl'=>'http://www.bhutanpost.com.bt/postcode/postcode.php',
    'zip'=>'\\d{5}',
    'zipex'=>'11001,31101,35003',
  ],
  'BV'=>[
    'name'=>'BOUVET ISLAND',
  ],
  'BW'=>[
    'name'=>'BOTSWANA',
  ],
  'BY'=>[
    'fmt'=>'%S%n%Z %C %X%n%A%n%O%n%N',
    'name'=>'BELARUS',
    'posturl'=>'http://zip.belpost.by',
    'zip'=>'\\d{6}',
    'zipex'=>'223016,225860,220050',
  ],
  'BZ'=>[
    'name'=>'BELIZE',
  ],
  'CA'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'lang'=>'en',
    'name'=>'CANADA',
    'posturl'=>'http://www.canadapost.ca/cpotools/apps/fpc/personal/findByCity?execution=e2s1',
    'require'=>'ACSZ',
    'upper'=>'ACNOSZ',
    'zip'=>'[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d',
    'zipex'=>'H3Z 2Y7,V8X 3X4,T0L 1K0,T0H 1A0,K1A 0B1',
  ],
  'CC'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'COCOS (KEELING) ISLANDS',
    'upper'=>'CS',
    'zip'=>'6799',
  ],
  'CD'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'CONGO (DEM. REP.)',
  ],
  'CF'=>[
    'name'=>'CENTRAL AFRICAN REPUBLIC',
  ],
  'CG'=>[
    'name'=>'CONGO (REP.)',
  ],
  'CH'=>[
    'fmt'=>'%O%n%N%n%A%nCH-%Z %C',
    'lang'=>'de',
    'name'=>'SWITZERLAND',
    'posturl'=>'http://www.post.ch/db/owa/pv_plz_pack/pr_main',
    'require'=>'ACZ',
    'upper'=>'',
    'zip'=>'\\d{4}',
    'zipex'=>'2544,1211,1556,3030',
  ],
  'CI'=>[
    'fmt'=>'%N%n%O%n%X %A %C %X',
    'name'=>'COTE D\'IVOIRE',
  ],
  'CK'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'COOK ISLANDS',
    'zip'=>'\\d{4}',
  ],
  'CL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'es',
    'name'=>'CHILE',
    'posturl'=>'http://www.correos.cl/SitePages/home.aspx',
    'state_name_type'=>'State',
    'zip'=>'\\d{7}',
    'zipex'=>'8340457,8720019,1230000,8329100,8720019',
  ],
  'CM'=>[
    'name'=>'CAMEROON',
  ],
  'CN'=>[
    'fmt'=>'%Z%n%S%C%D%n%A%n%O%n%N',
    'lang'=>'zh-hans',
    'name'=>'P.R. CHINA',
    'posturl'=>'http://www.cpdc.com.cn/postcdQueryAction.do?reqCode=gotoQueryPostAddr',
    'require'=>'ACSZ',
    'upper'=>'S',
    'zip'=>'\\d{6}',
    'zipex'=>'266033,317204,100096,100808',
  ],
  'CO'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'name'=>'COLOMBIA',
    'posturl'=>'http://www.codigopostal4-72.com.co/codigosPostales/',
    'zip'=>'\\d{6}',
    'zipex'=>'111221,130001,760011',
  ],
  'CR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'COSTA RICA',
    'posturl'=>'https://www.correos.go.cr/nosotros/codigopostal/busqueda.html',
    'zip'=>'\\d{4,5}|\\d{3}-\\d{4}',
    'zipex'=>'1000,2010,1001',
  ],
  'CS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
    'zipex'=>'11001',
  ],
  'CV'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'lang'=>'pt',
    'name'=>'CAPE VERDE',
    'state_name_type'=>'Island',
    'zip'=>'\\d{4}',
    'zipex'=>'7600',
  ],
  'CX'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'CHRISTMAS ISLAND',
    'upper'=>'CS',
    'zip'=>'6798',
  ],
  'CY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CYPRUS',
    'zip'=>'\\d{4}',
    'zipex'=>'2008,3304,1900',
  ],
  'CZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'CZECH REP.',
    'posturl'=>'http://psc.ceskaposta.cz/CleanForm.action',
    'zip'=>'\\d{3}[ ]?\\d{2}',
    'zipex'=>'100 00,251 66,530 87,110 00,225 99',
  ],
  'DE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GERMANY',
    'posturl'=>'http://www.postdirekt.de/plzserver/',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'26133,53225',
  ],
  'DJ'=>[
    'name'=>'DJIBOUTI',
  ],
  'DK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DENMARK',
    'posturl'=>'http://www.postdanmark.dk/da/Privat/Kundeservice/postnummerkort/Sider/Find-postnummer.aspx',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'8660,1566',
  ],
  'DM'=>[
    'name'=>'DOMINICA',
  ],
  'DO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'DOMINICAN REP.',
    'posturl'=>'http://inposdom.gob.do/servicios/codigo-postal.html#buscar_codigo',
    'zip'=>'\\d{5}',
    'zipex'=>'11903,10101',
  ],
  'DZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ALGERIA',
    'zip'=>'\\d{5}',
    'zipex'=>'40304,16027',
  ],
  'EC'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'ECUADOR',
    'upper'=>'CZ',
    'zip'=>'(?:[A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?',
    'zipex'=>'090105,EC090112,H0103C,P0133B,P0133A,P0133V',
  ],
  'EE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ESTONIA',
    'posturl'=>'http://www.post.ee/?op=sihtnumbriotsing',
    'zip'=>'\\d{5}',
    'zipex'=>'69501,11212',
  ],
  'EG'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'lang'=>'ar',
    'name'=>'EGYPT',
    'zip'=>'\\d{5}',
    'zipex'=>'12411,11599',
  ],
  'EH'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'WESTERN SAHARA',
    'zip'=>'\\d{5}',
    'zipex'=>'70000,72000',
  ],
  'ER'=>[
    'name'=>'ERITREA',
  ],
  'ES'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'SPAIN',
    'posturl'=>'http://www.correos.es/contenido/13-MenuRec2/04-MenuRec24/1010_s-CodPostal.asp',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'28039,28300,28070',
  ],
  'ET'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ETHIOPIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'FI'=>[
    'fmt'=>'%O%n%N%n%A%nFI-%Z %C',
    'name'=>'FINLAND',
    'posturl'=>'http://www.verkkoposti.com/e3/postinumeroluettelo',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'00550,00011',
  ],
  'FJ'=>[
    'name'=>'FIJI',
  ],
  'FK'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'FALKLAND ISLANDS (MALVINAS)',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'FIQQ 1ZZ',
    'zipex'=>'FIQQ 1ZZ',
  ],
  'FM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MICRONESIA (Federated State of)',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9694[1-4])(?:[ \\-](\\d{4}))?',
    'zipex'=>'96941,96944',
  ],
  'FO'=>[
    'fmt'=>'%N%n%O%n%A%nFO%Z %C',
    'name'=>'FAROE ISLANDS',
    'posturl'=>'http://www.postur.fo/',
    'zip'=>'\\d{3}',
    'zipex'=>'100',
  ],
  'FR'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRANCE',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'CX',
    'zip'=>'\\d{2}[ ]?\\d{3}',
    'zipex'=>'33380,34092,33506',
  ],
  'GA'=>[
    'name'=>'GABON',
  ],
  'GB'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'locality_name_type'=>'Town',
    'name'=>'UNITED KINGDOM',
    'posturl'=>'http://www.royalmail.com/postcode-finder',
    'require'=>'ACZ',
    'state_name_type'=>'County',
    'upper'=>'CZ',
    'zip'=>'GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}',
    'zipex'=>'EC1Y 8SY,GIR 0AA,M2 5BQ,M34 4AB,CR0 2YR,DN16 9AA,W1A 4ZZ,EC1A 1HQ,OX14 4PG,BS18 8HF,NR25 7HG,RH6 0NP,BH23 6AA,B6 5BA,SO23 9AP,PO1 3AX,BFPO 61',
  ],
  'GD'=>[
    'name'=>'GRENADA (WEST INDIES)',
  ],
  'GE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GEORGIA',
    'posturl'=>'http://www.georgianpost.ge/index.php?page=10',
    'zip'=>'\\d{4}',
    'zipex'=>'0101',
  ],
  'GF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'FRENCH GUIANA',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]3\\d{2}',
    'zipex'=>'97300',
  ],
  'GG'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%nGUERNSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'posturl'=>'http://www.guernseypost.com/postcode_finder/',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'GY1 1AA,GY2 2BT',
  ],
  'GH'=>[
    'name'=>'GHANA',
  ],
  'GI'=>[
    'fmt'=>'%N%n%O%n%A',
    'name'=>'GIBRALTAR',
    'require'=>'A',
    'zip'=>'GX11 1AA',
    'zipex'=>'GX11 1AA',
  ],
  'GL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREENLAND',
    'require'=>'ACZ',
    'zip'=>'39\\d{2}',
    'zipex'=>'3900,3950,3911',
  ],
  'GM'=>[
    'name'=>'GAMBIA',
  ],
  'GN'=>[
    'fmt'=>'%N%n%O%n%Z %A %C',
    'name'=>'GUINEA',
    'zip'=>'\\d{3}',
    'zipex'=>'001,200,100',
  ],
  'GP'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'GUADELOUPE',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'GQ'=>[
    'name'=>'EQUATORIAL GUINEA',
  ],
  'GR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GREECE',
    'posturl'=>'http://www.elta.gr/findapostcode.aspx',
    'require'=>'ACZ',
    'zip'=>'\\d{3} ?\\d{2}',
    'zipex'=>'151 24,151 10,101 88',
  ],
  'GS'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'SOUTH GEORGIA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'SIQQ 1ZZ',
    'zipex'=>'SIQQ 1ZZ',
  ],
  'GT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z- %C',
    'name'=>'GUATEMALA',
    'zip'=>'\\d{5}',
    'zipex'=>'09001,01501',
  ],
  'GU'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'GUAM',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
    'zipex'=>'96910,96931',
  ],
  'GW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'GUINEA-BISSAU',
    'zip'=>'\\d{4}',
    'zipex'=>'1000,1011',
  ],
  'GY'=>[
    'name'=>'GUYANA',
  ],
  'HK'=>[
    'fmt'=>'%S%n%A%n%O%n%N',
    'lang'=>'zh-hant',
    'name'=>'HONG KONG',
    'require'=>'AS',
    'state_name_type'=>'Area',
    'upper'=>'S',
  ],
  'HM'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'HEARD AND MCDONALD ISLANDS',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
  ],
  'HN'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S%n%Z',
    'name'=>'HONDURAS',
    'require'=>'ACS',
    'zip'=>'(?:\\d{5})?',
  ],
  'HR'=>[
    'fmt'=>'%N%n%O%n%A%nHR-%Z %C',
    'name'=>'CROATIA',
    'posturl'=>'http://www.posta.hr/default.aspx?pretpum',
    'zip'=>'\\d{5}',
    'zipex'=>'10000,21001,10002',
  ],
  'HT'=>[
    'fmt'=>'%N%n%O%n%A%nHT%Z %C %X',
    'name'=>'HAITI',
    'zip'=>'\\d{4}',
    'zipex'=>'6120,5310,6110,8510',
  ],
  'HU'=>[
    'fmt'=>'%N%n%O%n%C%n%A%n%Z',
    'name'=>'HUNGARY (Rep.)',
    'posturl'=>'http://posta.hu/ugyfelszolgalat/iranyitoszam_kereso',
    'upper'=>'ACNO',
    'zip'=>'\\d{4}',
    'zipex'=>'1037,2380,1540',
  ],
  'ID'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S %Z',
    'lang'=>'id',
    'name'=>'INDONESIA',
    'state_name_type'=>'District',
    'zip'=>'\\d{5}',
    'zipex'=>'40115',
  ],
  'IE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'en',
    'name'=>'IRELAND',
    'state_name_type'=>'County',
  ],
  'IL'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'ISRAEL',
    'posturl'=>'http://www.israelpost.co.il/zipcode.nsf/demozip?openform',
    'zip'=>'\\d{5}(?:\\d{2})?',
    'zipex'=>'9614303',
  ],
  'IM'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'ISLE OF MAN',
    'posturl'=>'http://www.gov.im/post/postal/fr_main.asp',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'IM2 1AA,IM99 1PS',
  ],
  'IN'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'INDIA',
    'posturl'=>'http://www.indiapost.gov.in/pin/pinsearch.aspx',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'zip'=>'\\d{6}',
    'zipex'=>'110034,110001',
  ],
  'IO'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'BRITISH INDIAN OCEAN TERRITORY',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'BBND 1ZZ',
    'zipex'=>'BBND 1ZZ',
  ],
  'IQ'=>[
    'fmt'=>'%O%n%N%n%A%n%C, %S%n%Z',
    'name'=>'IRAQ',
    'require'=>'ACS',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
  ],
  'IS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ICELAND',
    'posturl'=>'http://www.postur.is/cgi-bin/hsrun.exe/Distributed/vefur/vefur.htx;start=HS_landakort_postnumer',
    'zip'=>'\\d{3}',
    'zipex'=>'320,121,220,110',
  ],
  'IT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'it',
    'name'=>'ITALY',
    'posturl'=>'http://www.poste.it/online/cercacap/',
    'require'=>'ACSZ',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'00144,47037,39049',
  ],
  'JE'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%nJERSEY%n%Z',
    'name'=>'CHANNEL ISLANDS',
    'posturl'=>'http://www.jerseypost.com/tools/postcode-address-finder/',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex'=>'JE1 1AA,JE2 2BT',
  ],
  'JM'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S %X',
    'lang'=>'en',
    'name'=>'JAMAICA',
    'require'=>'ACS',
    'state_name_type'=>'Parish',
  ],
  'JO'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'JORDAN',
    'zip'=>'\\d{5}',
    'zipex'=>'11937,11190',
  ],
  'JP'=>[
    'fmt'=>'〒%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'ja',
    'name'=>'JAPAN',
    'posturl'=>'http://search.post.japanpost.jp/zipcode/',
    'require'=>'ACSZ',
    'state_name_type'=>'Prefecture',
    'upper'=>'S',
    'zip'=>'\\d{3}-?\\d{4}',
    'zipex'=>'154-0023,350-1106,951-8073,112-0001,208-0032,231-0012,951-8073',
  ],
  'KE'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'KENYA',
    'zip'=>'\\d{5}',
    'zipex'=>'20100,00100',
  ],
  'KG'=>[
    'fmt'=>'%Z %C %X%n%A%n%O%n%N',
    'name'=>'KYRGYZSTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'720001',
  ],
  'KH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'CAMBODIA',
    'zip'=>'\\d{5}',
    'zipex'=>'12203,14206,12000',
  ],
  'KI'=>[
    'fmt'=>'%N%n%O%n%A%n%S%n%C',
    'name'=>'KIRIBATI',
    'state_name_type'=>'Island',
    'upper'=>'ACNOS',
  ],
  'KM'=>[
    'name'=>'COMOROS',
    'upper'=>'AC',
  ],
  'KN'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S',
    'lang'=>'en',
    'name'=>'SAINT KITTS AND NEVIS',
    'require'=>'ACS',
    'state_name_type'=>'Island',
  ],
  'KR'=>[
    'fmt'=>'%S %C%D%n%A%n%O%n%N%n%Z',
    'lang'=>'ko',
    'name'=>'KOREA (REP.)',
    'posturl'=>'http://www.epost.go.kr/search/zipcode/search5.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'Do Si',
    'upper'=>'Z',
    'zip'=>'\\d{3}[\\-]\\d{3}',
    'zipex'=>'110-110,699-800',
  ],
  'KW'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KUWAIT',
    'zip'=>'\\d{5}',
    'zipex'=>'54541,54551,54404,13009',
  ],
  'KY'=>[
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'en',
    'name'=>'CAYMAN ISLANDS',
    'posturl'=>'http://www.caymanpost.gov.ky/portal/page?_pageid=3561,1&_dad=portal&_schema=PORTAL',
    'require'=>'AS',
    'state_name_type'=>'Island',
    'zip'=>'KY\\d-\\d{4}',
    'zipex'=>'KY1-1100,KY1-1702,KY2-2101',
  ],
  'KZ'=>[
    'fmt'=>'%Z%n%S%n%C%n%A%n%O%n%N',
    'name'=>'KAZAKHSTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'040900,050012',
  ],
  'LA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'LAO (PEOPLE\'S DEM. REP.)',
    'zip'=>'\\d{5}',
    'zipex'=>'01160,01000',
  ],
  'LB'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LEBANON',
    'zip'=>'(?:(?:\\d{4})(?:[ ]?(?:\\d{4}))?)?',
    'zipex'=>'2038 3054,1107 2810,1000',
  ],
  'LC'=>[
    'name'=>'SAINT LUCIA',
  ],
  'LI'=>[
    'fmt'=>'%O%n%N%n%A%nFL-%Z %C',
    'name'=>'LIECHTENSTEIN',
    'posturl'=>'http://www.post.ch/db/owa/pv_plz_pack/pr_main',
    'require'=>'ACZ',
    'zip'=>'(948[5-9])|(949[0-7])',
    'zipex'=>'9496,9491,9490,9485',
  ],
  'LK'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SRI LANKA',
    'posturl'=>'http://www.slpost.gov.lk/',
    'zip'=>'\\d{5}',
    'zipex'=>'20000,00100',
  ],
  'LR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %X',
    'name'=>'LIBERIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1000',
  ],
  'LS'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'LESOTHO',
    'zip'=>'\\d{3}',
    'zipex'=>'100',
  ],
  'LT'=>[
    'fmt'=>'%O%n%N%n%A%nLT-%Z %C',
    'name'=>'LITHUANIA',
    'posturl'=>'http://www.post.lt/lt/?id=316',
    'zip'=>'\\d{5}',
    'zipex'=>'04340,03500',
  ],
  'LU'=>[
    'fmt'=>'%O%n%N%n%A%nL-%Z %C',
    'name'=>'LUXEMBOURG',
    'posturl'=>'http://www.pt.lu/portal/services_en_ligne/recherche_codes_postaux',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'4750,2998',
  ],
  'LV'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %Z',
    'name'=>'LATVIA',
    'posturl'=>'http://www.pasts.lv/lv/uzzinas/nodalas/',
    'zip'=>'LV-\\d{4}',
    'zipex'=>'LV-1073,LV-1000',
  ],
  'LY'=>[
    'name'=>'LIBYA',
  ],
  'MA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MOROCCO',
    'zip'=>'\\d{5}',
    'zipex'=>'53000,10000,20050,16052',
  ],
  'MC'=>[
    'fmt'=>'%N%n%O%n%A%nMC-%Z %C %X',
    'name'=>'MONACO',
    'zip'=>'980\\d{2}',
    'zipex'=>'98000,98020,98011,98001',
  ],
  'MD'=>[
    'fmt'=>'%N%n%O%n%A%nMD-%Z %C',
    'name'=>'Rep. MOLDOVA',
    'zip'=>'\\d{4}',
    'zipex'=>'2012,2019',
  ],
  'ME'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MONTENEGRO',
    'zip'=>'8\\d{4}',
    'zipex'=>'81257,81258,81258,81217,84314,85366',
  ],
  'MF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'SAINT MARTIN',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78][01]\\d{2}',
    'zipex'=>'97100',
  ],
  'MG'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MADAGASCAR',
    'zip'=>'\\d{3}',
    'zipex'=>'501,101',
  ],
  'MH'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'MARSHALL ISLANDS',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969[67]\\d)(?:[ \\-](\\d{4}))?',
    'zipex'=>'96960,96970',
  ],
  'MK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'MACEDONIA',
    'zip'=>'\\d{4}',
    'zipex'=>'1314,1321,1443,1062',
  ],
  'ML'=>[
    'name'=>'MALI',
  ],
  'MN'=>[
    'fmt'=>'%N%n%O%n%A%n%S %C-%X%n%Z',
    'name'=>'MONGOLIA',
    'posturl'=>'http://www.zipcode.mn/',
    'zip'=>'\\d{5}',
    'zipex'=>'65030,65270',
  ],
  'MO'=>[
    'fmt'=>'%A%n%O%n%N',
    'name'=>'MACAO',
    'require'=>'A',
  ],
  'MP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'NORTHERN MARIANA ISLANDS',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(9695[012])(?:[ \\-](\\d{4}))?',
    'zipex'=>'96950,96951,96952',
  ],
  'MQ'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MARTINIQUE',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]2\\d{2}',
    'zipex'=>'97220',
  ],
  'MR'=>[
    'name'=>'MAURITANIA',
    'upper'=>'AC',
  ],
  'MS'=>[
    'name'=>'MONTSERRAT',
  ],
  'MT'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALTA',
    'posturl'=>'http://postcodes.maltapost.com/',
    'upper'=>'CZ',
    'zip'=>'[A-Z]{3}[ ]?\\d{2,4}',
    'zipex'=>'NXR 01,ZTN 05,GPO 01,BZN 1130,SPB 6031,VCT 1753',
  ],
  'MU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'MAURITIUS',
    'upper'=>'CZ',
    'zip'=>'(?:\\d{3}[A-Z]{2}\\d{3})?',
    'zipex'=>'742CU001',
  ],
  'MV'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'MALDIVES',
    'posturl'=>'http://www.maldivespost.com/?lid=10',
    'zip'=>'\\d{5}',
    'zipex'=>'20026',
  ],
  'MW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'MALAWI',
  ],
  'MX'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C, %S',
    'lang'=>'es',
    'name'=>'MEXICO',
    'posturl'=>'http://www.correosdemexico.gob.mx/ServiciosLinea/Paginas/ccpostales.aspx',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CSZ',
    'zip'=>'\\d{5}',
    'zipex'=>'02860,77520,06082',
  ],
  'MY'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%Z %C%n%S',
    'lang'=>'ms',
    'name'=>'MALAYSIA',
    'posturl'=>'http://www.pos.com.my/pos/homepage.aspx',
    'require'=>'ACZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'43000,50754,88990,50670',
  ],
  'MZ'=>[
    'fmt'=>'%N%n%O%n%A%n%C',
    'name'=>'MOZAMBIQUE',
    'zip'=>'\\d{4}',
    'zipex'=>'1102,1119,3212',
  ],
  'NA'=>[
    'name'=>'NAMIBIA',
  ],
  'NC'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'NEW CALEDONIA',
    'posturl'=>'http://poste.opt.nc/index.php?option=com_content&view=article&id=80&Itemid=131',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'988\\d{2}',
    'zipex'=>'98814,98800,98810',
  ],
  'NE'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'NIGER',
    'zip'=>'\\d{4}',
    'zipex'=>'8001',
  ],
  'NF'=>[
    'fmt'=>'%O%n%N%n%A%n%C %S %Z',
    'name'=>'NORFOLK ISLAND',
    'upper'=>'CS',
    'zip'=>'2899',
  ],
  'NG'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z%n%S',
    'lang'=>'en',
    'name'=>'NIGERIA',
    'posturl'=>'http://www.nigeriapostcodes.com/views/',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'(?:\\d{6})?',
    'zipex'=>'930283,300001,931104',
  ],
  'NI'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C, %S',
    'lang'=>'es',
    'name'=>'NICARAGUA',
    'posturl'=>'http://www.correos.gob.ni/index.php/codigo-postal-2',
    'state_name_type'=>'Department',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'52000',
  ],
  'NL'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C',
    'name'=>'NETHERLANDS',
    'posturl'=>'http://www.postnl.nl/voorthuis/',
    'require'=>'ACZ',
    'zip'=>'\\d{4}[ ]?[A-Z]{2}',
    'zipex'=>'1234 AB,2490 AA',
  ],
  'NO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'NORWAY',
    'posturl'=>'http://adressesok.posten.no/nb/postal_codes/search',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'0025,0107,6631',
  ],
  'NP'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'NEPAL',
    'posturl'=>'http://www.gpo.gov.np/postalcode.aspx',
    'zip'=>'\\d{5}',
    'zipex'=>'44601',
  ],
  'NR'=>[
    'fmt'=>'%N%n%O%n%A%n%S',
    'lang'=>'en',
    'name'=>'NAURU CENTRAL PACIFIC',
    'require'=>'AS',
    'state_name_type'=>'District',
  ],
  'NU'=>[
    'name'=>'NIUE',
  ],
  'NZ'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C %Z',
    'name'=>'NEW ZEALAND',
    'posturl'=>'http://www.nzpost.co.nz/Cultures/en-NZ/OnlineTools/PostCodeFinder/',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'6001,6015,6332,8252,1030',
  ],
  'OM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z%n%C',
    'name'=>'OMAN',
    'zip'=>'(PC )?\\d{3}',
    'zipex'=>'133,112,111',
  ],
  'PA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'PANAMA (REP.)',
    'upper'=>'CS',
  ],
  'PE'=>[
    'name'=>'PERU',
    'posturl'=>'http://www.serpost.com.pe/cpostal/codigo',
    'zip'=>'(?:LIMA \\d|CALLAO 0?)\\d|[0-2]\\d{4}',
    'zipex'=>'LIMA 23,LIMA 42,CALLAO 2,02001',
  ],
  'PF'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'name'=>'FRENCH POLYNESIA',
    'require'=>'ACSZ',
    'state_name_type'=>'Island',
    'upper'=>'CS',
    'zip'=>'987\\d{2}',
  ],
  'PG'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z %S',
    'name'=>'PAPUA NEW GUINEA',
    'require'=>'ACS',
    'zip'=>'\\d{3}',
    'zipex'=>'111',
  ],
  'PH'=>[
    'fmt'=>'%N%n%O%n%A%n%D, %C%n%Z %S',
    'lang'=>'en',
    'name'=>'PHILIPPINES',
    'posturl'=>'http://www.philpost.gov.ph/',
    'zip'=>'\\d{4}',
    'zipex'=>'1008,1050,1135,1207,2000,1000',
  ],
  'PK'=>[
    'fmt'=>'%N%n%O%n%A%n%C-%Z',
    'name'=>'PAKISTAN',
    'posturl'=>'http://www.pakpost.gov.pk/postcode/postcode.html',
    'zip'=>'\\d{5}',
    'zipex'=>'44000',
  ],
  'PL'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'POLAND',
    'posturl'=>'http://www.poczta-polska.pl/kody.php',
    'require'=>'ACZ',
    'zip'=>'\\d{2}-\\d{3}',
    'zipex'=>'00-950,05-470,48-300,32-015,00-940',
  ],
  'PM'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'ST. PIERRE AND MIQUELON',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]5\\d{2}',
    'zipex'=>'97500',
  ],
  'PN'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'PITCAIRN',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'PCRN 1ZZ',
    'zipex'=>'PCRN 1ZZ',
  ],
  'PR'=>[
    'fmt'=>'%N%n%O%n%A%n%C PR %Z',
    'name'=>'PUERTO RICO',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACZ',
    'upper'=>'ACNO',
    'zip'=>'(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
    'zipex'=>'00930',
  ],
  'PS'=>[
    'name'=>'PALESTINIAN TERRITORY',
  ],
  'PT'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PORTUGAL',
    'posturl'=>'http://www.ctt.pt/feapl_2/app/open/tools.jspx?tool=1',
    'require'=>'ACZ',
    'zip'=>'\\d{4}-\\d{3}',
    'zipex'=>'2725-079,1250-096,1201-950,2860-571,1208-148',
  ],
  'PW'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'PALAU',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(969(?:39|40))(?:[ \\-](\\d{4}))?',
    'zipex'=>'96940',
  ],
  'PY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'PARAGUAY',
    'zip'=>'\\d{4}',
    'zipex'=>'1536,1538,1209',
  ],
  'QA'=>[
    'name'=>'QATAR',
    'upper'=>'AC',
  ],
  'RE'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'REUNION',
    'posturl'=>'http://www.laposte.fr/Particulier/Utiliser-nos-outils-pratiques/Outils-et-documents/Trouvez-un-code-postal',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'9[78]4\\d{2}',
    'zipex'=>'97400',
  ],
  'RO'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ROMANIA',
    'posturl'=>'http://www.posta-romana.ro/zip_codes',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
    'zipex'=>'060274,061357,200716',
  ],
  'RS'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'REPUBLIC OF SERBIA',
    'posturl'=>'http://www.posta.rs/struktura/lat/aplikacije/pronadji/nadji-postu.asp',
    'zip'=>'\\d{5,6}',
    'zipex'=>'106314',
  ],
  'RU'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'name'=>'RUSSIAN FEDERATION',
    'posturl'=>'http://info.russianpost.ru/servlet/department',
    'require'=>'ACZ',
    'state_name_type'=>'Oblast',
    'upper'=>'AC',
    'zip'=>'\\d{6}',
    'zipex'=>'125075,247112,103375',
  ],
  'RW'=>[
    'name'=>'RWANDA',
    'upper'=>'AC',
  ],
  'SA'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z',
    'name'=>'SAUDI ARABIA',
    'zip'=>'\\d{5}',
    'zipex'=>'11564,11187,11142',
  ],
  'SB'=>[
    'name'=>'SOLOMON ISLANDS',
  ],
  'SC'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'name'=>'SEYCHELLES',
    'state_name_type'=>'Island',
    'upper'=>'S',
  ],
  'SE'=>[
    'fmt'=>'%O%n%N%n%A%nSE-%Z %C',
    'name'=>'SWEDEN',
    'posturl'=>'http://www.posten.se/sv/Kundservice/Sidor/Sok-postnummer-resultat.aspx',
    'require'=>'ACZ',
    'zip'=>'\\d{3}[ ]?\\d{2}',
    'zipex'=>'11455,12345,10500',
  ],
  'SG'=>[
    'fmt'=>'%N%n%O%n%A%nSINGAPORE %Z',
    'name'=>'REP. OF SINGAPORE',
    'posturl'=>'http://www.singpost.com.sg/quick_services/index.htm',
    'require'=>'AZ',
    'zip'=>'\\d{6}',
    'zipex'=>'546080,308125,408600',
  ],
  'SH'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'SAINT HELENA',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'(ASCN|STHL) 1ZZ',
    'zipex'=>'STHL 1ZZ',
  ],
  'SI'=>[
    'fmt'=>'%N%n%O%n%A%nSI- %Z %C',
    'name'=>'SLOVENIA',
    'zip'=>'\\d{4}',
    'zipex'=>'4000,1001,2500',
  ],
  'SJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SVALBARD AND JAN MAYEN ISLANDS',
    'posturl'=>'http://epab.posten.no/',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'9170',
  ],
  'SK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SLOVAKIA',
    'posturl'=>'http://psc.posta.sk',
    'zip'=>'\\d{3}[ ]?\\d{2}',
    'zipex'=>'010 01,023 14,972 48,921 01,975 99',
  ],
  'SL'=>[
    'name'=>'SIERRA LEONE',
  ],
  'SM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SAN MARINO',
    'posturl'=>'http://www.poste.it/online/cercacap/',
    'require'=>'AZ',
    'zip'=>'4789\\d',
    'zipex'=>'47890,47891,47895,47899',
  ],
  'SN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SENEGAL',
    'zip'=>'\\d{5}',
    'zipex'=>'12500,46024,16556,10000',
  ],
  'SO'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'so',
    'name'=>'SOMALIA',
    'require'=>'ACS',
    'upper'=>'ACS',
    'zip'=>'\\d{5}',
    'zipex'=>'09010,11010',
  ],
  'SR'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X%n%S',
    'lang'=>'nl',
    'name'=>'SURINAME',
    'upper'=>'AS',
  ],
  'ST'=>[
    'fmt'=>'%N%n%O%n%A%n%C %X',
    'name'=>'SAO TOME AND PRINCIPE',
  ],
  'SV'=>[
    'fmt'=>'%N%n%O%n%A%n%Z-%C%n%S',
    'lang'=>'es',
    'name'=>'EL SALVADOR',
    'require'=>'ACS',
    'upper'=>'CSZ',
    'zip'=>'CP [1-3][1-7][0-2]\\d',
    'zipex'=>'CP 1101',
  ],
  'SZ'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%Z',
    'name'=>'SWAZILAND',
    'posturl'=>'http://www.sptc.co.sz/swazipost/codes.php',
    'upper'=>'ACZ',
    'zip'=>'[HLMS]\\d{3}',
    'zipex'=>'H100',
  ],
  'TA'=>[
    'name'=>'TRISTAN DA CUNHA',
    'zip'=>'TDCU 1ZZ',
    'zipex'=>'TDCU 1ZZ',
  ],
  'TC'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%Z',
    'name'=>'TURKS AND CAICOS ISLANDS',
    'require'=>'ACZ',
    'upper'=>'CZ',
    'zip'=>'TKCA 1ZZ',
    'zipex'=>'TKCA 1ZZ',
  ],
  'TD'=>[
    'name'=>'CHAD',
  ],
  'TF'=>[
    'name'=>'FRENCH SOUTHERN TERRITORIES',
  ],
  'TG'=>[
    'name'=>'TOGO',
  ],
  'TH'=>[
    'fmt'=>'%N%n%O%n%A%n%D %C%n%S %Z',
    'lang'=>'th',
    'name'=>'THAILAND',
    'upper'=>'S',
    'zip'=>'\\d{5}',
    'zipex'=>'10150,10210',
  ],
  'TJ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TAJIKISTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'735450,734025',
  ],
  'TK'=>[
    'name'=>'TOKELAU',
  ],
  'TL'=>[
    'name'=>'TIMOR-LESTE',
  ],
  'TM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TURKMENISTAN',
    'zip'=>'\\d{6}',
    'zipex'=>'744000',
  ],
  'TN'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'TUNISIA',
    'posturl'=>'http://www.poste.tn/codes.php',
    'zip'=>'\\d{4}',
    'zipex'=>'1002,8129,3100,1030',
  ],
  'TO'=>[
    'name'=>'TONGA',
  ],
  'TR'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C/%S',
    'lang'=>'tr',
    'locality_name_type'=>'District',
    'name'=>'TURKEY',
    'posturl'=>'http://postakodu.ptt.gov.tr/',
    'require'=>'ACZ',
    'zip'=>'\\d{5}',
    'zipex'=>'01960,06101',
  ],
  'TT'=>[
    'name'=>'TRINIDAD AND TOBAGO',
  ],
  'TV'=>[
    'fmt'=>'%N%n%O%n%A%n%X%n%C%n%S',
    'lang'=>'tyv',
    'name'=>'TUVALU',
    'state_name_type'=>'Island',
    'upper'=>'ACS',
  ],
  'TW'=>[
    'fmt'=>'%Z%n%S%C%n%A%n%O%n%N',
    'lang'=>'zh-hant',
    'name'=>'TAIWAN',
    'posturl'=>'http://www.post.gov.tw/post/internet/f_searchzone/index.jsp?ID=190102',
    'require'=>'ACSZ',
    'state_name_type'=>'County',
    'zip'=>'\\d{3}(\\d{2})?',
    'zipex'=>'104,106,10603,40867',
  ],
  'TZ'=>[
    'name'=>'TANZANIA (UNITED REP.)',
    'zip'=>'\\d{4}',
    'zipex'=>'6090',
  ],
  'UA'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S%n%Z',
    'name'=>'UKRAINE',
    'posturl'=>'http://services.ukrposhta.com/postindex_new/',
    'require'=>'ACZ',
    'state_name_type'=>'Oblast',
    'zip'=>'\\d{5}',
    'zipex'=>'15432,01055,01001',
  ],
  'UG'=>[
    'name'=>'UGANDA',
  ],
  'UM'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'UNITED STATES MINOR OUTLYING ISLANDS',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACS',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'96898',
    'zipex'=>'96898',
  ],
  'US'=>[
    'fmt'=>'%N%n%O%n%A%n%C, %S %Z',
    'lang'=>'en',
    'name'=>'UNITED STATES',
    'posturl'=>'https://tools.usps.com/go/ZipLookupAction!input.action',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'CS',
    'zip'=>'(\\d{5})(?:[ \\-](\\d{4}))?',
    'zipex'=>'95014,22162-1010',
  ],
  'UY'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C %S',
    'lang'=>'es',
    'name'=>'URUGUAY',
    'posturl'=>'http://www.correo.com.uy/index.asp?codPag=codPost&switchMapa=codPost',
    'upper'=>'CS',
    'zip'=>'\\d{5}',
    'zipex'=>'11600',
  ],
  'UZ'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C%n%S',
    'name'=>'UZBEKISTAN',
    'posturl'=>'http://www.pochta.uz/index.php/uz/pochta-indekslari/9',
    'upper'=>'CS',
    'zip'=>'\\d{6}',
    'zipex'=>'702100,700000',
  ],
  'VA'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'VATICAN',
    'zip'=>'00120',
    'zipex'=>'00120',
  ],
  'VC'=>[
    'name'=>'SAINT VINCENT AND THE GRENADINES (ANTILLES)',
    'posturl'=>'http://www.svgpost.gov.vc/?option=com_content&view=article&id=3&Itemid=16',
    'zip'=>'VC\\d{4}',
    'zipex'=>'VC0100,VC0110,VC0400',
  ],
  'VE'=>[
    'fmt'=>'%N%n%O%n%A%n%C %Z, %S',
    'lang'=>'es',
    'name'=>'VENEZUELA',
    'posturl'=>'http://www.ipostel.gob.ve/nlinea/codigo_postal.php',
    'require'=>'ACS',
    'upper'=>'CS',
    'zip'=>'\\d{4}',
    'zipex'=>'1010,3001,8011,1020',
  ],
  'VG'=>[
    'name'=>'VIRGIN ISLANDS (BRITISH)',
    'require'=>'A',
    'zip'=>'VG\\d{4}',
    'zipex'=>'VG1110,VG1150,VG1160',
  ],
  'VI'=>[
    'fmt'=>'%N%n%O%n%A%n%C %S %Z',
    'name'=>'VIRGIN ISLANDS (U.S.)',
    'posturl'=>'http://zip4.usps.com/zip4/welcome.jsp',
    'require'=>'ACSZ',
    'state_name_type'=>'State',
    'upper'=>'ACNOS',
    'zip'=>'(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?',
    'zipex'=>'00802-1222,00850-9802',
  ],
  'VN'=>[
    'fmt'=>'%N%n%O%n%A%n%C%n%S',
    'lang'=>'vi',
    'name'=>'VIET NAM',
    'posturl'=>'http://postcode.vnpost.vn/services/search.aspx',
    'require'=>'AC',
    'zip'=>'\\d{6}',
    'zipex'=>'119415,136065,720344',
  ],
  'VU'=>[
    'name'=>'VANUATU',
  ],
  'WF'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'WALLIS AND FUTUNA ISLANDS',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'986\\d{2}',
    'zipex'=>'98600',
  ],
  'WS'=>[
    'name'=>'SAMOA',
  ],
  'XK'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'KOSOVO',
    'zip'=>'[1-7]\\d{4}',
    'zipex'=>'10000',
  ],
  'YE'=>[
    'name'=>'YEMEN',
    'require'=>'AC',
  ],
  'YT'=>[
    'fmt'=>'%O%n%N%n%A%n%Z %C %X',
    'name'=>'MAYOTTE',
    'require'=>'ACZ',
    'upper'=>'ACX',
    'zip'=>'976\\d{2}',
    'zipex'=>'97600',
  ],
  'YU'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'SERBIA AND MONTENEGRO',
    'zip'=>'\\d{5}',
    'zipex'=>'11001',
  ],
  'ZA'=>[
    'fmt'=>'%N%n%O%n%A%n%D%n%C%n%Z',
    'name'=>'SOUTH AFRICA',
    'posturl'=>'http://www.postoffice.co.za/tools/postalcode.html',
    'require'=>'ACZ',
    'zip'=>'\\d{4}',
    'zipex'=>'0083,1451,0001',
  ],
  'ZM'=>[
    'fmt'=>'%N%n%O%n%A%n%Z %C',
    'name'=>'ZAMBIA',
    'require'=>'AC',
    'zip'=>'\\d{5}',
    'zipex'=>'50100,50101',
  ],
  'ZW'=>[
    'name'=>'ZIMBABWE',
  ],
];
